require('dotenv').config();
const mongoose = require('mongoose');
const Place = require('../models/Place');
const City = require('../models/City');
const Country = require('../models/Country');

const MONGO_URI = process.env.MONGO_URI;

// ────────────────────────────────────────────────
// İTALYA
// ────────────────────────────────────────────────
const italyPlaces = [
  // Roma
  { countryCode: 'IT', cityName: 'Roma', name: 'Kolezyum', slug: 'kolezyum-roma', category: 'Tarihi', shortDescription: 'Antik dünyanın en büyük amfitiyatrosu.', description: 'MS 70-80 yılları arasında inşa edilen Kolezyum, 50.000-80.000 seyirci kapasitesiyle antik dünyanın en büyük amfitiyatrosudur. Gladyatör dövüşleri, hayvan avları ve halka açık gösterilere ev sahipliği yapmıştır. Roma\'nın ve İtalya\'nın en ikonik simgesi olarak UNESCO Dünya Mirası listesindedir.', latitude: 41.8902, longitude: 12.4922, address: 'Piazza del Colosseo, 1, Roma', rating: 4.8, reviewCount: 95000, visitDuration: '2-3 saat', entranceFee: '16 €', openingHours: '09:00-19:00', tags: ['UNESCO', 'Roma', 'amfitiyatro', 'gladyatör', 'antik'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&h=500&fit=crop' },
  { countryCode: 'IT', cityName: 'Roma', name: 'Vatikan Müzeleri ve Sistine Şapeli', slug: 'vatikan-muzesi-sistine', category: 'Müze', shortDescription: 'Michelangelo\'nun şaheseri ve dünyanın en zengin müzesi.', description: 'Vatikan Müzeleri, 500 yılı aşkın süredir biriktirilen sanat eserlerinin sergilendiği dünyanın en zengin müze komplekslerinden biridir. Sistine Şapeli\'ndeki Michelangelo\'nun Yaratılış sahnesi ve Son Yargı freski insanlığın sanat mirasının zirvesidir. Raphael odaları ve antika galerileriyle birlikte gezilmesi gereken muazzam bir koleksiyondur.', latitude: 41.9065, longitude: 12.4536, address: 'Viale Vaticano, Vatikan', rating: 4.8, reviewCount: 72000, visitDuration: '3-4 saat', entranceFee: '17 €', openingHours: '09:00-18:00 (Pazar kapalı)', tags: ['UNESCO', 'sanat', 'Michelangelo', 'dini', 'fresk'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=800&h=500&fit=crop' },
  { countryCode: 'IT', cityName: 'Roma', name: 'Trevi Çeşmesi', slug: 'trevi-cesmesi', category: 'Tarihi', shortDescription: 'Dünyanın en ünlü barok çeşmesi.', description: 'Trevi Çeşmesi, 1762 yılında tamamlanmış, Nicola Salvi tarafından tasarlanmış görkemli bir barok şaheserdir. 26 metre yüksekliği ve 49 metre genişliğiyle Roma\'nın en büyük çeşmesidir. Efsaneye göre çeşmeye bozuk para atan kişi, Roma\'ya döner. Her yıl yaklaşık 1,5 milyon euro madeni para çeşmeden toplanarak hayır kurumlarına bağışlanır.', latitude: 41.9009, longitude: 12.4833, address: 'Piazza di Trevi, Roma', rating: 4.7, reviewCount: 68000, visitDuration: '30-45 dk', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['barok', 'çeşme', 'efsane', 'fotoğraf', 'turizm'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=800&h=500&fit=crop' },
  { countryCode: 'IT', cityName: 'Roma', name: 'Pantheon', slug: 'pantheon-roma', category: 'Tarihi', shortDescription: 'Dünyanın en iyi korunmuş antik yapısı.', description: 'Pantheon, MS 125 yılında İmparator Hadrian tarafından yaptırılmış, antik dünyanın en iyi korunmuş yapılarından biridir. 43.3 metre çapındaki kubbesi, yapılışından bu yana hâlâ dünyanın en büyük takviyesiz beton kubbesidir. Raphael başta olmak üzere birçok önemli İtalyan sanatçı ve kral burada medfundur.', latitude: 41.8986, longitude: 12.4769, address: 'Piazza della Rotonda, Roma', rating: 4.7, reviewCount: 58000, visitDuration: '30-60 dk', entranceFee: '5 €', openingHours: '09:00-19:00', tags: ['antik', 'Roma', 'kubbe', 'mimari', 'tapınak'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&h=500&fit=crop' },
  // Floransa
  { countryCode: 'IT', cityName: 'Floransa', name: 'Uffizi Galerisi', slug: 'uffizi-galerisi', category: 'Müze', shortDescription: 'Dünyanın en önemli İtalyan Rönesans sanat koleksiyonu.', description: 'Uffizi Galerisi, Botticelli\'nin Venüs\'ün Doğuşu ve İlkbahar eserleri başta olmak üzere Leonardo da Vinci, Michelangelo, Raphael ve Caravaggio gibi ustaların şaheserlerini barındırır. Cosimo de Medici tarafından 1560 yılında inşa ettirilen saray, 1765\'te halka açık müze haline getirilmiştir. Dünyanın en büyük ve en önemli sanat galerilerinden biridir.', latitude: 43.7677, longitude: 11.2553, address: 'Piazzale degli Uffizi, 6, Floransa', rating: 4.8, reviewCount: 42000, visitDuration: '2-4 saat', entranceFee: '20 €', openingHours: '08:15-18:50 (Pazartesi kapalı)', tags: ['müze', 'Rönesans', 'Botticelli', 'Da Vinci', 'sanat'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=500&fit=crop' },
  { countryCode: 'IT', cityName: 'Floransa', name: 'Floransa Katedrali (Duomo)', slug: 'floransa-katedrali-duomo', category: 'Tarihi', shortDescription: 'Brunelleschi\'nin devrimsel kubbesi ve Rönesans\'ın simgesi.', description: 'Santa Maria del Fiore Katedrali, Floransa\'nın gökyüzüne hakim 114.5 metre yüksekliğindeki devrimsel kubbeye sahip ikonik yapısıdır. Filippo Brunelleschi\'nin 1436\'da tamamladığı bu kubbe, modern mühendisliğin öncüsü kabul edilir. Katedrali kaplayan yeşil, pembe ve beyaz mermerler ile giotto çan kulesi birlikte Floransa\'nın en çok ziyaret edilen sitidir.', latitude: 43.7731, longitude: 11.2560, address: 'Piazza del Duomo, Floransa', rating: 4.8, reviewCount: 51000, visitDuration: '1-2 saat', entranceFee: '18 € (kubbe dahil)', openingHours: '10:00-17:00', tags: ['katedral', 'Rönesans', 'kubbe', 'Brunelleschi', 'mimari'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1543429776-2782fc8e9bce?w=800&h=500&fit=crop' },
  // Venedik
  { countryCode: 'IT', cityName: 'Venedik', name: 'Büyük Kanal ve Gondol Turu', slug: 'venedik-gondol-turu', category: 'Kültür', shortDescription: 'Dünyanın en romantik su yolu üzerinde efsanevi gondol deneyimi.', description: 'Venedik\'in ana caddesi olan Grand Canal (Büyük Kanal), 3.8 km uzunluğuyla şehri ikiye böler. Kanalın kıyısında sıralanan saraylar, kiliseler ve pazar alanları Venedik\'in tarihini gözler önüne serer. Gondollar ile yapılan tur, uzun ömürlü Venedik geleneğini yaşatmaktadır. Özellikle gün batımında yapılan gondol turları son derece romantiktir.', latitude: 45.4408, longitude: 12.3340, address: 'Grand Canal, Venedik', rating: 4.8, reviewCount: 44000, visitDuration: '1-2 saat', entranceFee: '80 € (gondol)', openingHours: '09:00-19:00', tags: ['gondol', 'kanal', 'romantik', 'Venedik', 'deniz'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800&h=500&fit=crop' },
  { countryCode: 'IT', cityName: 'Venedik', name: 'San Marco Meydanı ve Bazilikası', slug: 'san-marco-meydani', category: 'Tarihi', shortDescription: 'Napolyon\'un \'dünyanın oturma odası\' dediği eşsiz meydan.', description: 'San Marco Meydanı, Venedik\'in kalbidir. Napolyon\'un "Avrupa\'nın oturma odası" olarak nitelendirdiği bu meydan; 9. yüzyıldan kalma Aziz Markos Bazilikası, Campanile çan kulesi, Doge Sarayı ve antik kütüphane ile çevrilidir. Bizans mozaikleriyle süslü Bazilika\'nın içi nefes kesen bir güzelliğe sahiptir.', latitude: 45.4341, longitude: 12.3388, address: 'Piazza San Marco, Venedik', rating: 4.8, reviewCount: 61000, visitDuration: '2-3 saat', entranceFee: 'Ücretsiz (bazı bölümler ücretli)', openingHours: '09:30-17:15', tags: ['meydan', 'bazilika', 'Bizans', 'mozaik', 'Venedik'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?w=800&h=500&fit=crop' },
  // Milano
  { countryCode: 'IT', cityName: 'Milano', name: 'Milano Katedrali (Duomo di Milano)', slug: 'milano-katedrali', category: 'Tarihi', shortDescription: 'İtalya\'nın en büyük gotik katedrali, 135 kulesiyle ihtişamlı.', description: 'Milano Katedrali, 1386\'da inşasına başlanmış ve yaklaşık 500 yıl süren yapımla 1965\'te tamamlanabilmiştir. 135 kulesi, 3.400\'den fazla heykeli ve 11.700 m² yüzeyindeki nefes kesen vitray pencereleriyle dünyanın en büyük gotik katedrali kabul edilir. Damını çevreleyen teraslar, Milano\'nun panoramik manzarasını sunar.', latitude: 45.4641, longitude: 9.1919, address: 'Piazza del Duomo, Milano', rating: 4.8, reviewCount: 53000, visitDuration: '1-2 saat', entranceFee: '3-15 € (terasa göre)', openingHours: '08:00-19:00', tags: ['gotik', 'katedral', 'mimari', 'teras', 'Milano'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1520175480921-4edfa2983e0f?w=800&h=500&fit=crop' },
  // Napoli
  { countryCode: 'IT', cityName: 'Napoli', name: 'Pompeii Antik Kenti', slug: 'pompeii-antik-kenti', category: 'Tarihi', shortDescription: 'Vezüv\'ün külü altında donarak kalan antik Roma şehri.', description: 'Pompeii, MS 79 yılında Vezüv Yanardağı\'nın patlamasıyla volkanik kül altında kalmış ve yaklaşık 2.000 yıl boyunca göm olmuş etkileyici bir antik Roma şehridir. 1748\'de başlayan kazılar, dönemin yapılarını, mozaiklerini, duvar yazılarını ve mağazalarını gün yüzüne çıkarmıştır. UNESCO Dünya Mirası listesindedir.', latitude: 40.7506, longitude: 14.4989, address: 'Via Villa dei Misteri, 2, Pompei/Napoli', rating: 4.7, reviewCount: 38000, visitDuration: '3-5 saat', entranceFee: '16 €', openingHours: '09:00-19:00', tags: ['UNESCO', 'antik', 'volkan', 'Roma', 'arkeoloji'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1565117531832-fd4ad4f46e97?w=800&h=500&fit=crop' },
];

// ────────────────────────────────────────────────
// JAPONYA
// ────────────────────────────────────────────────
const japanPlaces = [
  // Tokyo
  { countryCode: 'JP', cityName: 'Tokyo', name: 'Senso-ji Tapınağı', slug: 'senso-ji-tapinagi', category: 'Tarihi', shortDescription: 'Tokyo\'nun en eski ve en çok ziyaret edilen Budist tapınağı.', description: 'Senso-ji, Tokyo\'nun Asakusa semtinde yer alan ve 645 yılında inşa edilmiş olan Japonya\'nın en eski ve en büyük Budist tapınaklarından biridir. Nakamise alışveriş koridoru, beş katlı pagoda ve Kaminarimon kapısıyla ünlüdür. Her yıl 30 milyonu aşkın ziyaretçiyle Tokyo\'nun en popüler turistik yeridir.', latitude: 35.7148, longitude: 139.7967, address: '2-3-1 Asakusa, Taito, Tokyo', rating: 4.7, reviewCount: 87000, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '06:00-17:00', tags: ['tapınak', 'Budist', 'tarihi', 'Asakusa', 'Japon kültürü'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&h=500&fit=crop' },
  { countryCode: 'JP', cityName: 'Tokyo', name: 'Shibuya Geçidi', slug: 'shibuya-gecidi', category: 'Kültür', shortDescription: 'Dünyanın en yoğun yaya geçidi, Tokyo\'nun nabzı.', description: 'Shibuya Scramble Crossing, dünyanın en yoğun yaya geçididir. Her ışık değişiminde 3.000\'den fazla kişi altı farklı yönden aynı anda karşıya geçmektedir. Çevreleyen neon tabelalar, dev ekranlar ve kalabalık Shibuya\'yı modern Japon şehir yaşamının sembolü haline getirmiştir. Ünlü Hachiko heykelinin bulunduğu meydan da buradadır.', latitude: 35.6595, longitude: 139.7004, address: 'Shibuya Crossing, Tokyo', rating: 4.6, reviewCount: 62000, visitDuration: '30-60 dk', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['modern', 'neon', 'yaya', 'ikonik', 'Tokyo'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&h=500&fit=crop' },
  { countryCode: 'JP', cityName: 'Tokyo', name: 'Tokyo Kulesi', slug: 'tokyo-kulesi', category: 'Tarihi', shortDescription: '333 metrelik çelik kule, Tokyo\'nun ikonik silueti.', description: 'Tokyo Kulesi, 1958 yılında inşa edilen ve Eyfel Kulesi\'nden ilham alan 333 metrelik çelik bir yayın kulesinin ve gözlem kulesidir. Kırmızı-beyaz renkli kulesi, Tokyo\'nun geleneksel -ve modern- siluetlerine karışmış en tanınan simgelerden biridir. İki farklı yükseklikte gözlem platformundan Fuji Dağı\'na kadar gören panoramik manzara izlenebilir.', latitude: 35.6586, longitude: 139.7454, address: '4-2-8 Shibakoen, Minato, Tokyo', rating: 4.5, reviewCount: 41000, visitDuration: '1-2 saat', entranceFee: '1,200 ¥', openingHours: '09:00-23:00', tags: ['kule', 'manzara', 'ikonik', 'panorama', 'Tokyo'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&h=500&fit=crop' },
  // Kyoto
  { countryCode: 'JP', cityName: 'Kyoto', name: 'Fushimi Inari Tapınağı', slug: 'fushimi-inari-tapinagi', category: 'Tarihi', shortDescription: 'Binlerce turuncu torii kapısıyla kaplı kutsal yol.', description: 'Fushimi Inari, çıkışta dağın zirvesine kadar uzanan binlerce turuncu torii kapısı (geçiş kapısı) ile dünyanın en etkileyici ve en fotoğrafçısına en çok ilham veren tapınak alanlarından biridir. Tahta tilki (kitsune) heykelleri ile ünlü olan bu yer, İnari tanrısına adanmıştır. Tüm yürüyüş yaklaşık 2-3 saat sürer ve etkileyici manzaralar sunar.', latitude: 34.9671, longitude: 135.7727, address: '68 Fukakusa Yabunouchicho, Fushimi, Kyoto', rating: 4.8, reviewCount: 71000, visitDuration: '2-3 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['tapınak', 'torii', 'Shinto', 'yürüyüş', 'fotoğraf'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&h=500&fit=crop' },
  { countryCode: 'JP', cityName: 'Kyoto', name: 'Kinkaku-ji (Altın Köşk)', slug: 'kinkakuji-altin-kosk', category: 'Tarihi', shortDescription: 'Göl yüzeyine yansıyan altın kaplı Zen tapınağı.', description: 'Kinkaku-ji (Rokuon-ji), üst iki katı saf altın varaklı Japon gururu tapınağıdır. 1397\'de inşa edilen köşk, çevreleyen bahçe ve gölü üzerine yansıyan altın görüntüsüyle Japonya\'nın en çok fotoğraflanan yerlerinden biridir. UNESCO Dünya Mirası listesindedir. 1950\'de çılgın bir keşiş tarafından yakılmış, 1955\'te aynısı yeniden inşa edilmiştir.', latitude: 35.0394, longitude: 135.7292, address: '1 Kinkakujicho, Kita, Kyoto', rating: 4.8, reviewCount: 68000, visitDuration: '1-2 saat', entranceFee: '500 ¥', openingHours: '09:00-17:00', tags: ['UNESCO', 'altın', 'tapınak', 'Zen', 'göl'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=800&h=500&fit=crop' },
  { countryCode: 'JP', cityName: 'Kyoto', name: 'Arashiyama Bambu Korusu', slug: 'arashiyama-bambu-korusu', category: 'Doğa', shortDescription: 'Yükselen bambu sütunları arasında yürüyüş deneyimi.', description: 'Arashiyama Bambu Korusu, Kyoto\'nun batısında yer alan ve gökyüzüne uzanan bambu sütunlarından oluşan büyüleyici bir parkurdur. Bambu gövdelerinin birbirine sürtünmesinden çıkan esrarlı uğultu, doğanın en eşsiz seslerinden biridir. Japon hükümetine göre bu ses, Japonya\'nın korunması gereken 100 sesinden biridir. Yakınındaki Tenryu-ji tapınağıyla birlikte ziyaret edilmesi önerilir.', latitude: 35.0172, longitude: 135.6762, address: 'Sagaogurayama Tabuchiyamacho, Ukyo, Kyoto', rating: 4.7, reviewCount: 55000, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['bambu', 'doğa', 'orman', 'yürüyüş', 'fotoğraf'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&h=500&fit=crop' },
  // Osaka
  { countryCode: 'JP', cityName: 'Osaka', name: 'Osaka Kalesi', slug: 'osaka-kalesi', category: 'Tarihi', shortDescription: 'Japon birliğinin sembolü, kiraz çiçekleri sezonunda büyülü.', description: 'Osaka Kalesi, 1583 yılında Toyotomi Hideyoshi tarafından yaptırılmış ve Japonya\'nın en ikonik kalelerinden biridir. 5 katlı ana kule, etrafındaki hendekler ve surlarlayan 13 km\'lik surlarıyla Osaka\'nın en büyük parkının ortasında yükselmektedir. Kiraz çiçeği (sakura) sezonunda kale bahçeleri muhteşem bir pembe griye bürünür.', latitude: 34.6873, longitude: 135.5259, address: 'Osakajo, Chuo, Osaka', rating: 4.6, reviewCount: 49000, visitDuration: '2-3 saat', entranceFee: '600 ¥', openingHours: '09:00-17:00', tags: ['kale', 'tarihi', 'sakura', 'park', 'Osaka'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800&h=500&fit=crop' },
  // Hiroshima
  { countryCode: 'JP', cityName: 'Hiroshima', name: 'Barış Anıtı Parkı', slug: 'baris-aniti-parki-hiroshima', category: 'Tarihi', shortDescription: 'Nükleer bombanın simgesi Atom Bombası Kubbesi ve güçlü barış mesajı.', description: 'Hiroshima Barış Anıtı Parkı, 6 Ağustos 1945\'te atılan atom bombasının kurbanlarını anmak için inşa edilmiştir. Bombanın merkezine yalnızca 160 metre uzaklıkta ayakta kalan Genbaku (Atom Bombası) Kubbesi, UNESCO Dünya Mirası listesindedir. Barış Anıtı Müzesi, insanlığın en karanlık saatlerine ışık tutan derin bir deneyim sunar.', latitude: 34.3955, longitude: 132.4526, address: '1-2 Nakajima-cho, Naka, Hiroshima', rating: 4.9, reviewCount: 37000, visitDuration: '2-3 saat', entranceFee: '200 ¥ (müze)', openingHours: '08:30-18:00', tags: ['UNESCO', 'barış', 'tarih', 'anıt', 'müze'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&h=500&fit=crop' },
  // Nara
  { countryCode: 'JP', cityName: 'Nara', name: 'Todai-ji Tapınağı ve Nara Geyikleri', slug: 'todaiji-tapinagi-nara', category: 'Tarihi', shortDescription: 'Dünyanın en büyük ahşap yapısı ve serbest dolaşan geyikler.', description: 'Todai-ji, MS 752 yılında inşa edilen ve dünyanın en büyük ahşap yapısı olan tapınaktır. İçindeki 15 metre yüksekliğindeki dev Buda heykeli (Daibutsu) ziyaretçilerini şaşırtır. Tapınak parkında yüzlerce evcil Sika geyiği serbestçe dolaşmakta ve ziyaretçilerle etkileşime geçmektedir. Geyikler, Japonya\'nın ulusal sembolleri arasındadır.', latitude: 34.6887, longitude: 135.8399, address: '406-1 Zoshicho, Nara', rating: 4.8, reviewCount: 42000, visitDuration: '2-3 saat', entranceFee: '600 ¥', openingHours: '07:30-17:30', tags: ['tapınak', 'geyik', 'Buda', 'ahşap', 'UNESCO'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=500&fit=crop' },
];

// ────────────────────────────────────────────────
// FRANSA
// ────────────────────────────────────────────────
const francePlaces = [
  // Paris
  { countryCode: 'FR', cityName: 'Paris', name: 'Eyfel Kulesi', slug: 'eyfel-kulesi', category: 'Tarihi', shortDescription: 'Dünyanın en tanınan yapısı, Paris\'in ebedi simgesi.', description: 'Eyfel Kulesi, 1889 Dünya Fuarı için Gustave Eiffel tarafından tasarlanan ve o dönemde dünyanın en yüksek yapısı olan ikonik demir kafes kulesini temsil eder. 330 metre yüksekliğiyle Paris\'in en önemli simgesidir. Her yıl 7 milyondan fazla ziyaretçiyle dünyanın en çok ziyaret edilen ücretli anıt yapısıdır. Geceleyin ışıl ışıl parlar.', latitude: 48.8584, longitude: 2.2945, address: 'Champ de Mars, 5 Av. Anatole France, Paris', rating: 4.7, reviewCount: 132000, visitDuration: '1-2 saat', entranceFee: '11-29 €', openingHours: '09:00-00:45', tags: ['ikonik', 'kule', 'manzara', 'Paris', 'romantik'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800&h=500&fit=crop' },
  { countryCode: 'FR', cityName: 'Paris', name: 'Louvre Müzesi', slug: 'louvre-muzesi', category: 'Müze', shortDescription: 'Dünyanın en büyük ve en çok ziyaret edilen sanat müzesi.', description: 'Louvre Müzesi, 73.000 m² sergi alanında 38.000\'den fazla sanat eserini barındıran dünyanın en büyük sanat müzesidir. Mona Lisa, Venüs de Milo ve Samothrace\'li Zafer başlıca çekicilikleridir. Ortaçağdan 21. yüzyıla uzanan koleksiyonu, insan uygarlığının sanat tarihini kapsamlıdır. Piramit girişi ise modern mimarlığın simgesi haline gelmiştir.', latitude: 48.8606, longitude: 2.3376, address: 'Rue de Rivoli, Paris', rating: 4.8, reviewCount: 95000, visitDuration: '3-5 saat', entranceFee: '17 €', openingHours: '09:00-18:00 (Salı kapalı)', tags: ['müze', 'sanat', 'Mona Lisa', 'Da Vinci', 'dünya mirası'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&h=500&fit=crop' },
  { countryCode: 'FR', cityName: 'Paris', name: 'Notre-Dame Katedrali', slug: 'notre-dame-katedrali', category: 'Tarihi', shortDescription: 'Gotik mimarinin şaheseri, 850 yıllık tarihin tanığı.', description: 'Notre-Dame de Paris Katedrali, 1163-1345 yılları arasında inşa edilmiş Fransız Gotik mimarisinin en güzel örneklerinden biridir. 2019 yangınında büyük hasar gören katedral, kapsamlı restorasyon sürecinden geçerek 2024\'te yeniden ziyarete açılmıştır. Notre-Dame, Victor Hugo\'nun romanıyla dünya edebiyatına da girmiş edebi bir simgedir.', latitude: 48.8530, longitude: 2.3499, address: '6 Parvis Notre-Dame, Paris', rating: 4.8, reviewCount: 78000, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '07:45-18:45', tags: ['gotik', 'katedral', 'mimari', 'tarihi', 'UNESCO'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1478391679764-b2d8b3cd1e94?w=800&h=500&fit=crop' },
  { countryCode: 'FR', cityName: 'Paris', name: 'Versailles Sarayı', slug: 'versailles-sarayi', category: 'Tarihi', shortDescription: 'XIV. Louis\'nin güç ve ihtişamın doruk noktası olan sarayı.', description: 'Versailles Sarayı, 1682\'den 1789\'a kadar Fransız krallık ailesinin ikametgahı olarak hizmet vermiştir. 700 odalı saray; Aynalar Galerisi, Büyük Trianon köşkü ve Fransız barok bahçe sanatının şaheseri olan geometrik bahçe düzenlemesiyle UNESCO Dünya Mirası listesindedir. Sarayın bahçeleri 800 hektarı aşan bir alana yayılmaktadır.', latitude: 48.8049, longitude: 2.1204, address: 'Place d\'Armes, 78000 Versailles', rating: 4.8, reviewCount: 62000, visitDuration: '3-5 saat', entranceFee: '18 €', openingHours: '09:00-17:30 (Pazartesi kapalı)', tags: ['UNESCO', 'saray', 'bahçe', 'barok', 'kraliyet'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1597924850977-3052e8c2d2c4?w=800&h=500&fit=crop' },
  // Nice
  { countryCode: 'FR', cityName: 'Nice', name: 'Promenade des Anglais', slug: 'promenade-des-anglais', category: 'Doğa', shortDescription: 'Azure kıyısının ikonik sahil promenadı.', description: 'Promenade des Anglais, Akdeniz kıyısı boyunca uzanan 7 km\'lik meşhur sahil yoludur. İlk kez 1820\'de İngiliz turistler tarafından yaptırılan bu yol, bugün Nice\'in en belirleyici özelliğidir. Turquoise-mavi deniz, beyaz çakıl taşları ve palmiye sıraları boyunca yürüyüş, koşu ya da bisiklet sürülür. Fransız Rivierası\'nın simgesidir.', latitude: 43.6952, longitude: 7.2673, address: 'Promenade des Anglais, Nice', rating: 4.6, reviewCount: 28000, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['sahil', 'promenade', 'Riviera', 'Akdeniz', 'yürüyüş'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=800&h=500&fit=crop' },
  // Bordeaux
  { countryCode: 'FR', cityName: 'Bordeaux', name: 'Bordeaux Bağları Turu', slug: 'bordeaux-baglari-turu', category: 'Kültür', shortDescription: 'Dünyanın en seçkin şarap bölgesinde üzüm bağları gezisi.', description: 'Bordeaux ve çevresindeki bağlar, Médoc, Saint-Émilion, Pomerol ve Sauternes gibi dünyaca ünlü appellations\'larla çevrilmiştir. Dünyaca ünlü şatolar (château\'lar) ziyarete açık eğitimli rehabların eşliğinde şarap tadımı turları düzenler. Saint-Émilion kasabası da UNESCO listesindedir. Fransız gastronomi kültürünü yakından tanımanın harika bir yoludur.', latitude: 44.8378, longitude: -0.5792, address: 'Bordeaux Bağ Bölgesi, Fransa', rating: 4.7, reviewCount: 18000, visitDuration: 'Tam gün', entranceFee: 'Değişken', openingHours: 'Bağa göre değişir', tags: ['şarap', 'bağ', 'gastronomi', 'UNESCO', 'kültür'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=800&h=500&fit=crop' },
];

// ────────────────────────────────────────────────
// İSPANYA
// ────────────────────────────────────────────────
const spainPlaces = [
  // Barcelona
  { countryCode: 'ES', cityName: 'Barcelona', name: 'Sagrada Familia', slug: 'sagrada-familia', category: 'Tarihi', shortDescription: 'Gaudí\'nin 140 yıldır inşa edilen başyapıtı.', description: 'Sagrada Familia, Antoni Gaudí\'nin 1882\'de başladığı ve hâlâ inşaat devam eden muazzam Katalan Gotik bazilikasıdır. Doğanın formlarından esinlenen organik mimari dili, iç mekanındaki renkli vitray pencereler ve cephedeki ayrıntılı heykeller bu yapıyı dünyanın en benzersiz dini yapısı olarak öne çıkarır. UNESCO Dünya Mirası listesindedir.', latitude: 41.4036, longitude: 2.1744, address: 'C/ de Mallorca, 401, Barcelona', rating: 4.9, reviewCount: 88000, visitDuration: '1-2 saat', entranceFee: '26 €', openingHours: '09:00-20:00', tags: ['UNESCO', 'Gaudí', 'bazilika', 'gotik', 'mimari'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1583779457094-ab6f77f7bf57?w=800&h=500&fit=crop' },
  { countryCode: 'ES', cityName: 'Barcelona', name: 'Park Güell', slug: 'park-guell', category: 'Doğa', shortDescription: 'Gaudí\'nin doğa ile büyülü bir buluşmayı tasarladığı park.', description: 'Park Güell, Antoni Gaudí tarafından 1900-1914 yılları arasında tasarlanmış UNESCO korumasındaki açık hava sanat parkıdır. Renkli mozaik seramik heykeller, sütunlu yürüyüş yolları ve Barselona manzarasını sunan grand teras, parkın en ikonik öğeleridir. İçinde Gaudí\'nin eski evi, şimdi müze olarak ziyaretçilere açıktır.', latitude: 41.4145, longitude: 2.1527, address: 'Carrer d\'Olot, s/n, Barcelona', rating: 4.7, reviewCount: 64000, visitDuration: '1-2 saat', entranceFee: '10 €', openingHours: '09:30-19:30', tags: ['UNESCO', 'Gaudí', 'park', 'mozaik', 'manzara'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&h=500&fit=crop' },
  { countryCode: 'ES', cityName: 'Barcelona', name: 'La Barceloneta Plajı', slug: 'barceloneta-plaji', category: 'Plaj', shortDescription: 'Barselona\'nın ikonik kentsel plajı.', description: 'La Barceloneta, Barselona\'nın şehir merkezine yakın en ünlü plaj mahallesiydir. 1.1 km uzunluğundaki bu plaj, güneşlenmeden çöpçekaneler oynamaya, canlı müzik dinlemeye, sörf yapmaya kadar pek çok aktivite imkanı sunar. Plaj boyunca sıralanan restoranlar ve chiringuito\'lar (plaj barları) Katalonya mutfağını tattırır.', latitude: 41.3781, longitude: 2.1910, address: 'Barceloneta, Barcelona', rating: 4.5, reviewCount: 41000, visitDuration: 'Yarım - Tam gün', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['plaj', 'deniz', 'eğlence', 'Barcelona', 'yaz'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1529154166925-574a0236a4f4?w=800&h=500&fit=crop' },
  // Madrid
  { countryCode: 'ES', cityName: 'Madrid', name: 'Prado Müzesi', slug: 'prado-muzesi', category: 'Müze', shortDescription: 'İspanyol ve Avrupa sanatının en büyük koleksiyonu.', description: 'Prado Müzesi, Goya, Velázquez ve El Greco\'nun başyapıtları başta olmak üzere 8.000\'den fazla tabloyu barındıran İspanya\'nın milli sanat galerisiysi ve Avrupa\'nın en önemli müzelerinden biridir. 1819\'dan bu yana halka açık olan müze, Ortaçağ\'dan 19. yüzyıla kadar uzanan zengin bir koleksiyon sunar. Velázquez\'in "Las Meninas" eseri müzenin en ünlü tablosudur.', latitude: 40.4138, longitude: -3.6922, address: 'C/ de Ruiz de Alarcón, 23, Madrid', rating: 4.8, reviewCount: 52000, visitDuration: '2-4 saat', entranceFee: '15 €', openingHours: '10:00-20:00', tags: ['müze', 'sanat', 'Goya', 'Velázquez', 'İspanyol'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1565177051602-b62c7ecf4a5b?w=800&h=500&fit=crop' },
  // Granada
  { countryCode: 'ES', cityName: 'Granada', name: 'Alhambra Sarayı', slug: 'alhambra-sarayi', category: 'Tarihi', shortDescription: 'İslam mimarisinin Batı\'da yarattığı en büyük harika.', description: 'Alhambra, 13-14. yüzyıllarda Nasrid Hanedanı tarafından inşa edilmiş eşsiz bir Endülüs İslam sarayı ve kale kompleksidir. İnce Mudéjar oymaları, muazzam taçlı kemerler ve Sultan Saray bölmesindeki Aslanlar Avlusu, dünyanın en büyüleyici mimari başarılarından sayılır. UNESCO Dünya Mirası listesindedir ve yıllık 2.7 milyon ziyaretçi ağırlar.', latitude: 37.1760, longitude: -3.5881, address: 'Calle Real de la Alhambra, Granada', rating: 4.9, reviewCount: 74000, visitDuration: '3-4 saat', entranceFee: '14 €', openingHours: '08:00-20:00', tags: ['UNESCO', 'İslam', 'saray', 'Endülüs', 'mimari'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&h=500&fit=crop' },
  // Sevilla
  { countryCode: 'ES', cityName: 'Sevilla', name: 'Sevilla Katedrali ve La Giralda', slug: 'sevilla-katedrali-giralda', category: 'Tarihi', shortDescription: 'Dünyanın en büyük gotik katedrali, eski minaresiyle.', description: 'Sevilla Katedrali, 1401-1528 yılları arasında önceki Moorish caminin temelleri üzerine inşa edilmiştir ve dünyanın en büyük gotik katedrali unvanını taşımaktadır. Eski cami minaresinden dönüştürülen La Giralda çan kulesi, Sevilla\'nın siluetine hakim olan simgedir. Kristof Kolomb\'un mezarı da katedralde bulunmaktadır. UNESCO listesindedir.', latitude: 37.3862, longitude: -5.9925, address: 'Av. de la Constitución, s/n, Sevilla', rating: 4.8, reviewCount: 46000, visitDuration: '1-2 saat', entranceFee: '12 €', openingHours: '11:00-17:00 (Pazar sabah ibadet)', tags: ['UNESCO', 'katedral', 'gotik', 'Moor', 'Kolomb'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1559662780-c3bab6f7e00b?w=800&h=500&fit=crop' },
];

// ────────────────────────────────────────────────
// BREZİLYA
// ────────────────────────────────────────────────
const brazilPlaces = [
  // Rio de Janeiro
  { countryCode: 'BR', cityName: 'Rio de Janeiro', name: 'Kurtarıcı İsa Heykeli', slug: 'kurtarici-isa-heykeli', category: 'Tarihi', shortDescription: 'Dünya\'nın yedi yeni harikasından biri.', description: 'Kurtarıcı İsa (Cristo Redentor), 1931\'de Corcovado Dağı\'nın tepesinde inşa edilmiş 30 metre yüksekliğindeki Brezilya\'nın ve Rio\'nun en ikonik yapısıdır. Kollarını açmış pozisyonu şehri ve Guanabara Körfezi\'ni kucaklarken ziyaretçilerine unutulmaz panoramik manzar sunar. Dünyanın Yeni Yedi Harikası\'ndan biri olarak kabul edilmektedir.', latitude: -22.9519, longitude: -43.2105, address: 'Parque Nacional da Tijuca, Rio de Janeiro', rating: 4.8, reviewCount: 82000, visitDuration: '2-3 saat', entranceFee: 'R$ 87', openingHours: '08:00-21:00', tags: ['ikonik', 'heykel', 'manzara', 'dünya harikası', 'Rio'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&h=500&fit=crop' },
  { countryCode: 'BR', cityName: 'Rio de Janeiro', name: 'Copacabana Plajı', slug: 'copacabana-plaji', category: 'Plaj', shortDescription: 'Dünyanın en ünlü 4 km\'lik şehir plajı.', description: 'Copacabana Plajı, dünyanın en ünlü kentsel plajıdır. 4 km uzunluğundaki bu kumsal, yıl boyunca futbol (fut-vôlei), dalgacılar ve güneş banyocularıyla dolar. Önündeki mozaik kaldırım (calçadão), dondurma satıcıları ve beach bar\'larıyla canlı bir atmosfer sunar. Yeni Yıl kutlamaları Copacabana\'da düzenlenen havai fişek gösterisiyle ünlüdür.', latitude: -22.9710, longitude: -43.1823, address: 'Copacabana, Rio de Janeiro', rating: 4.6, reviewCount: 61000, visitDuration: 'Yarım - Tam gün', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['plaj', 'deniz', 'sörf', 'Rio', 'güneş'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=800&h=500&fit=crop' },
  { countryCode: 'BR', cityName: 'Rio de Janeiro', name: 'Sugarloaf Dağı (Pão de Açúcar)', slug: 'sugarloaf-dagi', category: 'Doğa', shortDescription: 'Guanabara Körfezi\'ne hakim efsanevi granit tepe.', description: 'Pão de Açúcar (Şeker Ekmeği), Rio de Janeiro\'nun simgesi olan granit kayalığı ve zirvesinden izlenen panoramik manzarasıyla ünlüdür. 396 metre yükseklikteki zirveye iki aşamalı teleferik hattı ile ulaşılır. Üstten Kurtarıcı İsa heykeli, Copacabana, Ipanema ve Guanabara Körfezi\'nin tamamı görünür. Gün batımı saatlerinde izlenmekte en iyi deneyim sunulur.', latitude: -22.9490, longitude: -43.1566, address: 'Praia Vermelha, Rio de Janeiro', rating: 4.7, reviewCount: 48000, visitDuration: '2-3 saat', entranceFee: 'R$ 140', openingHours: '09:00-21:00', tags: ['teleferik', 'manzara', 'granit', 'Rio', 'gün batımı'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&h=500&fit=crop' },
  // Manaus
  { countryCode: 'BR', cityName: 'Manaus', name: 'Amazon Ormanları Turu', slug: 'amazon-ormanlari-turu', category: 'Doğa', shortDescription: 'Dünyanın akciğeri, eşsiz flora ve fauna keşfi.', description: 'Manaus, Amazon Ormanı\'nın kalbine açılan kapıdır. Buradan düzenlenen tekne ve kano turlarıyla Amazon\'un biyolojik çeşitliliği keşfedilebilir. Pembe nehir yunusları (boto), gagalı timsahlar, dev nilüferler ve egzotik kuşlar bu ormanda yaşayan canlıların yalnızca küçük bir bölümüdür. Rio Negro ve Solimões nehirlerinin birleştiği "Suyun Buluşması" noktası da görülmeye değerdir.', latitude: -3.1190, longitude: -60.0217, address: 'Amazon Ormanı, Manaus çevresi', rating: 4.8, reviewCount: 29000, visitDuration: '1-3 gün', entranceFee: 'Tur paketine göre', openingHours: 'Tur programına göre', tags: ['Amazon', 'orman', 'tropikal', 'yaban hayatı', 'doğa'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1468493858157-0da44aaf1d13?w=800&h=500&fit=crop' },
  // Brasília
  { countryCode: 'BR', cityName: 'Brasília', name: 'Brezilya Kongre Binası', slug: 'brezilya-kongre-binasi', category: 'Kültür', shortDescription: 'Oscar Niemeyer\'in modernist başyapıtı, planlı başkentin kalbi.', description: 'Brezilya Kongre Binası, Oscar Niemeyer tarafından tasarlanmış ve 1960\'ta tamamlanmış Brezilya\'nın siyasi merkezidir. İki kule ve iki çanak (Senato ve Meclis) ile oluşan yapı, modernist mimarinin başyapıtı olarak kabul edilir. Tüm Brasília merkezi, UNESCO Dünya Mirası statüsündedir. Şehir kuş bakışı görüldüğünde bir uçağı andırmaktadır.', latitude: -15.7997, longitude: -47.8639, address: 'Praça dos Três Poderes, Brasília', rating: 4.6, reviewCount: 19000, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '09:00-17:00 (hafta içi)', tags: ['UNESCO', 'mimari', 'Niemeyer', 'modernist', 'siyasi'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1551865784-5c48e7793890?w=800&h=500&fit=crop' },
  // Salvador
  { countryCode: 'BR', cityName: 'Salvador', name: 'Pelourinho Tarihi Merkezi', slug: 'pelourinho-salvador', category: 'Tarihi', shortDescription: 'Afrika-Brezilya ruhunun yansıdığı renkli sömürge sokakları.', description: 'Pelourinho, Salvador\'un UNESCO korumasındaki tarihi merkezridir. Portekiz sömürge döneminden kalma renkli cepheli yapılar, barok kiliseler ve dar taş döşeli sokakları ile büyüleyen bir atmosfer sunar. Afro-Brezilya kültürünün en canlı yaşandığı bu semtte Capoeira gösterileri, Candomblé dini törenleri ve yerel restoranlar bulunmaktadır.', latitude: -12.9747, longitude: -38.5096, address: 'Pelourinho, Salvador, Bahia', rating: 4.6, reviewCount: 22000, visitDuration: '2-3 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['UNESCO', 'sömürge', 'Afro-Brezilya', 'kültür', 'tarihi'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop' },
];

// ────────────────────────────────────────────────
// MISIR
// ────────────────────────────────────────────────
const egyptPlaces = [
  // Giza
  { countryCode: 'EG', cityName: 'Giza', name: 'Büyük Piramitler ve Sfenks', slug: 'buyuk-piramitler-sfenks', category: 'Tarihi', shortDescription: 'Antik dünyanın yedi harikasından hayatta kalan tek yapı.', description: 'Giza Piramitleri ve Büyük Sfenks, yaklaşık MÖ 2560-2500 yılları arasında inşa edilmiş insanlığın en büyük mühendislik mucizelerinden biridir. Büyük Keops Piramidi, orijinal yüksekliği 146 metre ile binlerce yıl boyunca dünyanın en yüksek yapısıydı. Sfenks ise antik Mısır\'ın en tanınan simgesidir. UNESCO Dünya Mirası listesindedir.', latitude: 29.9792, longitude: 31.1342, address: 'Al Haram, Giza', rating: 4.8, reviewCount: 97000, visitDuration: '3-4 saat', entranceFee: '200 EGP', openingHours: '08:00-17:00', tags: ['UNESCO', 'piramit', 'sfenks', 'antik Mısır', 'dünya harikası'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&h=500&fit=crop' },
  // Luxor
  { countryCode: 'EG', cityName: 'Luxor', name: 'Karnak Tapınak Kompleksi', slug: 'karnak-tapinagi', category: 'Tarihi', shortDescription: 'Dünyada hâlâ ayakta duran en büyük dini yapı kompleksi.', description: 'Karnak, MÖ 2000-30 arasında farklı firavunlar tarafından inşa edilmiş devasa tapınak kompleksidir. 200 hektardan fazla alana yayılan kompleks; Büyük Hipostil Salonu (134 dev sütun), obeliskler, sfenks sütun yolları ve kutsal göl içerir. Işık ve ses gösterisi her gece ziyaretçilere antik Mısır\'ın gizemini yansıtır.', latitude: 25.7188, longitude: 32.6573, address: 'Karnak, Luxor', rating: 4.8, reviewCount: 43000, visitDuration: '2-3 saat', entranceFee: '220 EGP', openingHours: '06:00-17:30', tags: ['tapınak', 'obelisk', 'antik Mısır', 'firavun', 'sütun'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=500&fit=crop' },
  { countryCode: 'EG', cityName: 'Luxor', name: 'Krallar Vadisi', slug: 'krallar-vadisi', category: 'Tarihi', shortDescription: 'Firavunların son uyku yeri, Tutankamon\'un mezarı.', description: 'Krallar Vadisi, Yeni Krallık döneminde (MÖ 1550-1070) 63 firavun ve asil mezarının oyulduğu yer olarak bilinmektedir. Tutankamon\'un 1922\'de Howard Carter tarafından keşfedilen lam gömülü, altın kaplı hazine manzarası arkeoloji tarihinin en büyük keşfiydi. Renkli hiyeroglifler ve duvar resimleriyle süslenmiş koridorlar ziyaretçileri büyüler.', latitude: 25.7402, longitude: 32.6014, address: 'Gurna, Luxor', rating: 4.7, reviewCount: 38000, visitDuration: '2-3 saat', entranceFee: '240 EGP', openingHours: '06:00-17:00', tags: ['antik Mısır', 'mezar', 'Tutankamon', 'firavun', 'arkeoloji'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&h=500&fit=crop' },
  // Kahire
  { countryCode: 'EG', cityName: 'Kahire', name: 'Mısır Müzesi', slug: 'misir-muzesi-kahire', category: 'Müze', shortDescription: 'Dünyanın en büyük antik Mısır eserler koleksiyonu.', description: 'Mısır Müzesi, Tahrir Meydanı\'nda yer alan ve 120.000\'den fazla antik Mısır eserini barındıran dünyanın en büyük Mısır arkeoloji müzesidir. Tutankamon\'un altın maskesi, tahta koltukları ve 5.000 yıllık mummilerin sergilendiği müze, antik Mısır medeniyetini kavramak için en iyi başlangıç noktasıdır. Yakınlarda yeni inşa edilen Büyük Mısır Müzesi (GEM) de ziyarete açılmaktadır.', latitude: 30.0478, longitude: 31.2336, address: 'Tahrir Square, Kahire', rating: 4.7, reviewCount: 51000, visitDuration: '2-4 saat', entranceFee: '200 EGP', openingHours: '09:00-17:00', tags: ['müze', 'antik Mısır', 'Tutankamon', 'mumya', 'arkeoloji'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=800&h=500&fit=crop' },
  // Sharm El Sheikh
  { countryCode: 'EG', cityName: 'Sharm El Sheikh', name: 'Kızıldeniz\'de Dalış ve Şnorkeling', slug: 'kizildeniz-dalis-sharm', category: 'Doğa', shortDescription: 'Dünyanın en zengin mercan resif ekosistemi.', description: 'Sharm El Sheikh\'teki Kızıldeniz, dünyanın en zengin ve en renkli mercan resiflerinden birine ev sahipliği yapar. 1.200\'den fazla balık türü, 1.000\'i aşkın omurgasız ve yüzlerce mercan türüyle hem dalış yapanlar hem de şnorkeling tutkunları için cennet niteliğindedir. Ras Mohammed Milli Parkı ve Tiran Boğazı en popüler dalış noktalarındandır.', latitude: 27.9158, longitude: 34.3300, address: 'Sharm El Sheikh, Sinai', rating: 4.8, reviewCount: 33000, visitDuration: '1-2 gün', entranceFee: 'Tur fiyatına göre', openingHours: 'Gün boyunca', tags: ['dalış', 'mercan', 'deniz', 'Kızıldeniz', 'yaban hayatı'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1560275619-4cc5fa59d3ae?w=800&h=500&fit=crop' },
  // Aswan
  { countryCode: 'EG', cityName: 'Aswan', name: 'Philae Tapınağı', slug: 'philae-tapinagi-aswan', category: 'Tarihi', shortDescription: 'Nil\'de bir adaya kurtarılmış antik Mısır tapınağı.', description: 'Philae Tapınağı, İsis Tanrıçası\'na adanmış muhteşem bir antik Mısır tapınağıdır. Aswan Barajı\'nın inşasında su altında kalma tehlikesiyle karşılaşınca UNESCO tarafından düzenlenen kurtarma operasyonuyla mevcuttan 500 m uzaktaki Agilkia Adası\'na taşınmıştır. Tekneyle ulaşılan tapınak, palmiyeler ve Nil manzarası eşliğinde eşsiz bir ortamda bulunmaktadır.', latitude: 24.0271, longitude: 32.8849, address: 'Agilkia Island, Aswan', rating: 4.7, reviewCount: 22000, visitDuration: '1-2 saat', entranceFee: '180 EGP', openingHours: '07:00-16:00', tags: ['tapınak', 'antik Mısır', 'ada', 'UNESCO', 'Nil'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&h=500&fit=crop' },
];

// ────────────────────────────────────────────────
// AVUSTRALYA
// ────────────────────────────────────────────────
const australiaPlaces = [
  // Sydney
  { countryCode: 'AU', cityName: 'Sydney', name: 'Sydney Opera Binası', slug: 'sydney-opera-binasi', category: 'Kültür', shortDescription: 'Dünyanın en tanınan 20. yüzyıl yapısı.', description: 'Sydney Opera Binası, Danimarkalı mimar Jørn Utzon tarafından tasarlanan ve 1973\'te tamamlanan ikonik yapıdır. Yelken biçimindeki kabukları, Sydney Limanı\'ndan görüldüğünde benzersiz bir siluet oluşturur. Her yıl 8 milyonu aşkın ziyaretçi ağırlayan Opera Binası, dünyanın en aktif gösteri merkezlerinden biridir ve UNESCO Dünya Mirası listesindedir.', latitude: -33.8568, longitude: 151.2153, address: 'Bennelong Point, Sydney', rating: 4.8, reviewCount: 79000, visitDuration: '1-3 saat', entranceFee: '43 AU$ (tur)', openingHours: '09:00-17:00', tags: ['UNESCO', 'mimari', 'opera', 'ikonik', 'liman'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1523428096881-5bd79d043006?w=800&h=500&fit=crop' },
  { countryCode: 'AU', cityName: 'Sydney', name: 'Sydney Harbour Bridge', slug: 'sydney-harbour-bridge', category: 'Tarihi', shortDescription: 'Dünyanın en geniş uzun açıklıklı köprüsü.', description: 'Sydney Harbour Bridge, 1932 yılında açılan ve dünyanın en büyük çelik kemer köprüsüdür. Yerel halk arasında "askı" olarak da bilinen köprü, Sydney\'in siluetinin ayrılmaz bir parçasıdır. Köprü tırmanma turu (BridgeClimb) ile zirveye çıkarken 360° panoramik Sydney manzarası izlenebilir. Her yeni yılda köprü üzerinde görkemli havai fişek gösterileri yapılır.', latitude: -33.8523, longitude: 151.2108, address: 'Bradfield Hwy, Sydney', rating: 4.8, reviewCount: 64000, visitDuration: '1-3 saat', entranceFee: '174 AU$ (tırmanma)', openingHours: '24 saat (tırmanma: 07:00-19:00)', tags: ['köprü', 'ikonik', 'manzara', 'tırmanma', 'Sydney'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop' },
  // Cairns
  { countryCode: 'AU', cityName: 'Cairns', name: 'Büyük Set Resifi', slug: 'buyuk-set-resifi', category: 'Doğa', shortDescription: 'Dünyanın en büyük mercan resif ekosistemi.', description: 'Büyük Set Resifi, 2.900\'den fazla bireysel resif ve 900 adadan oluşan 344.400 km² yüzey alanıyla dünyanın en büyük canlı yapısıdır. Bu eşsiz ekosistem; 1.500\'den fazla balık türü, 4.000 yumuşakça türü ve 200\'den fazla kuş türüne ev sahipliği yapar. UNESCO Dünya Doğal Mirası olarak tescilli olan bu alan, uzaydan bile görülebilmektedir.', latitude: -16.2864, longitude: 145.7294, address: 'Büyük Set Resifi, Queensland', rating: 4.9, reviewCount: 56000, visitDuration: '1-3 gün', entranceFee: 'Tur fiyatına göre (50-250 AU$)', openingHours: 'Gündüz saatleri', tags: ['UNESCO', 'mercan', 'dalış', 'deniz', 'yaban hayatı'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=500&fit=crop' },
  // Melbourne
  { countryCode: 'AU', cityName: 'Melbourne', name: 'Federation Square', slug: 'federation-square-melbourne', category: 'Kültür', shortDescription: 'Melbourne\'un kültürel kalbi, canlı şehir meydanı.', description: 'Federation Square, Melbourne\'un merkezinde modern mimarisiyle çarpıcı bir görünüm sunan sosyal ve kültürel buluşma noktasıdır. NGV\'nin Avustralya koleksiyonu, ACMI (Avustralya Sinema ve Medya Müzesi), pek çok restoran, kafe ve galeri meydanın çevresini oluşturur. Önemli etkinliklerin, sirk gösterilerinin ve konserlerinin sahnesi olan meydan ücretsiz Wi-Fi hizmetiyle de hizmet vermektedir.', latitude: -37.8179, longitude: 144.9690, address: 'Swanston St, Melbourne', rating: 4.5, reviewCount: 31000, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['müze', 'kültür', 'meydan', 'sinema', 'sanat'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1514395462725-fb4566210144?w=800&h=500&fit=crop' },
  // Darwin
  { countryCode: 'AU', cityName: 'Darwin', name: 'Kakadu Milli Parkı', slug: 'kakadu-milli-parki-darwin', category: 'Doğa', shortDescription: 'Dünyanın en büyük milli parkı, Aboriginal kaya resimleri ve tropikal yaban hayatı.', description: 'Kakadu Milli Parkı, 19.804 km²\'lik alanıyla dünyanın en büyük milli parklarından biridir. 20.000 yıllık Aboriginal kaya resimleri, timsahlar, kanguruların ve 280 kuş türünün yaşadığı ıslak otlaklar, kanyonlar ve şelalelerden oluşan olağanüstü bir ekosisteme sahiptir. UNESCO Dünya Mirası olarak hem doğal hem de kültürel önemiyle çifte liste alan nadir yerlerden biridir.', latitude: -12.6651, longitude: 132.5264, address: 'Kakadu Milli Parkı, Northern Territory', rating: 4.8, reviewCount: 24000, visitDuration: '2-5 gün', entranceFee: '40 AU$', openingHours: '24 saat', tags: ['UNESCO', 'milli park', 'Aboriginal', 'yaban hayatı', 'doğa'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop' },
  // Perth
  { countryCode: 'AU', cityName: 'Perth', name: 'Rottnest Island', slug: 'rottnest-island-perth', category: 'Doğa', shortDescription: 'Gülümseyen Quokka\'ların adası, muhteşem sahiller.', description: 'Rottnest Adası, Perth\'e yaklaşık 18 km mesafede, feribotle ulaşılabilen güzel bir doğa adacığıdır. Adanın en büyük çekiciliği, "dünyanın en mutlu hayvanı" olarak bilinen ve gülümseyerek poz veriyor gibi görünen Quokka\'lardır. 63 plaj ve 20 koyu ile adanın kıyıları olağanüstü turkuaz sulara sahiptir. Araba yasak; bisikletle keşfedilir.', latitude: -31.9997, longitude: 115.5251, address: 'Rottnest Island, Batı Avustralya', rating: 4.7, reviewCount: 22000, visitDuration: '1-2 gün', entranceFee: '30 AU$ (feribot dahil değil)', openingHours: '24 saat', tags: ['ada', 'quokka', 'plaj', 'bisiklet', 'doğa'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=800&h=500&fit=crop' },
];

// ────────────────────────────────────────────────
// ALMANYA
// ────────────────────────────────────────────────
const germanyPlaces = [
  // Berlin
  { countryCode: 'DE', cityName: 'Berlin', name: 'Brandenburg Kapısı', slug: 'brandenburg-kapisi', category: 'Tarihi', shortDescription: 'Alman birliğinin ve özgürlüğünün sembolü.', description: 'Brandenburg Kapısı, 1791 yılında neo-klasik tarzda inşa edilmiş ve 20. yüzyılda Almanya\'nın bölünmüşlüğünün ardından birleşiminin en güçlü sembolü haline gelmiş ikonik kapıdır. Berlin Duvarı\'nın yıkıldığı 1989 gecesi üzerinde kutlama yapılan kapı, Almanya\'nın uluslararası alanda en tanınan tarihi simgesidir. Doğu-Batı arasındaki bu kapı, günümüzde hâlâ tarihi önemi ve büyüklüğüyle ziyaretçileri etkiler.', latitude: 52.5163, longitude: 13.3777, address: 'Pariser Platz, Berlin', rating: 4.7, reviewCount: 68000, visitDuration: '30-60 dk', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['tarihi', 'kapı', 'Almanya', 'birleşme', 'Berlin'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1587330979470-3595ac045ab0?w=800&h=500&fit=crop' },
  { countryCode: 'DE', cityName: 'Berlin', name: 'Holocaust Anıtı', slug: 'holocaust-aniti-berlin', category: 'Tarihi', shortDescription: 'Katledilen Avrupa Yahudilerine adanmış 2.711 beton steladan oluşan anıt.', description: 'Holocaust Anıtı (Soykırım Anıtı), 19.073 m² alan üzerinde farklı yükseklikte 2.711 beton steladan oluşan ve katledilen Avrupa Yahudilerinin anısına inşa edilmiş benzersiz bir anıt yapıdır. Peters Eisenman tarafından tasarlanan yapı, ziyaretçilere yöneldiği içinden geçerek deneyimlenmek üzere tasarlanmıştır. Yer altındaki Bilgi Merkezi katledilen Yahudilerin bireysel hikâyelerini aktarır.', latitude: 52.5136, longitude: 13.3788, address: 'Cora-Berliner-Straße 1, Berlin', rating: 4.7, reviewCount: 41000, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat (müze 10:00-20:00)', tags: ['anıt', 'tarihi', 'soykırım', 'müze', 'insanlık'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=500&fit=crop' },
  // Münih
  { countryCode: 'DE', cityName: 'Münih', name: 'Neuschwanstein Şatosu', slug: 'neuschwanstein-satosu', category: 'Tarihi', shortDescription: 'Peri masallarından fırlamış romantik romantik yüzyıl şatosu.', description: 'Neuschwanstein Şatosu, Bavyera\'nın Alp dağlarının üzerinde yükselen ve Walt Disney\'in Uyuyan Güzel Şatosu\'na ilham veren romantik bir şatodur. Kral II. Ludwig tarafından 1868\'de yaptırılmaya başlanan ve hiç tamamlanamamış şato, yılda 1.3 milyon ziyaretçi çekmektedir. İçindeki muazzam sahneler, Ortaçağ sembolistikleri ve panoramik Alp manzarası ziyaretçileri büyüler.', latitude: 47.5576, longitude: 10.7498, address: 'Neuschwansteinstraße 20, Schwangau', rating: 4.8, reviewCount: 74000, visitDuration: '2-4 saat', entranceFee: '15 €', openingHours: '09:00-18:00', tags: ['şato', 'Bavyera', 'romantik', 'Alp', 'Walt Disney'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1604580864964-0462f5d5b1a8?w=800&h=500&fit=crop' },
  { countryCode: 'DE', cityName: 'Münih', name: 'Marienplatz ve Yeni Belediye Binası', slug: 'marienplatz-yeni-belediye', category: 'Tarihi', shortDescription: 'Münih\'in kalbi, saat kuleli neo-gotik belediye binası.', description: 'Marienplatz, Münih\'in merkezi meydanı ve tourist merkezi konumdadır. Neo-Gotik tarzda inşa edilen Yeni Belediye Binası\'ndaki Glockenspiel (carillon), her gün 11:00 ve (yaz aylarında) 17:00\'da dönen figürlerle müzik çalan ünlü saat kulesini barındırır. Meydan aynı zamanda Münih\'in geleneksel Noel pazarının ve diğer önemli şehir etkinliklerinin sahnesidir.', latitude: 48.1374, longitude: 11.5755, address: 'Marienplatz 1, München', rating: 4.7, reviewCount: 52000, visitDuration: '30-60 dk', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['meydan', 'belediye', 'Glockenspiel', 'Noel', 'Münih'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1554072675-66db59dba46f?w=800&h=500&fit=crop' },
  // Köln
  { countryCode: 'DE', cityName: 'Köln', name: 'Köln Katedrali', slug: 'koln-katedrali', category: 'Tarihi', shortDescription: 'Dünya\'nın 3. büyük gotik katedrali, UNESCO Dünya Mirası.', description: 'Köln Katedrali, 1248 yılında inşasına başlanmış, ancak ancak 1880\'de tamamlanabilen Ren Gotik mimarisinin şaheseridir. 157 metre yüksekliğiyle açıklandığı dönemde dünyanın en yüksek yapısıydı. Ren nehri kıyısındaki konumu ve iki siyah kulesiyle Köln\'ün siluetine damga vurmaktadır. UNESCO Dünya Mirası ve UNESCO tehlikeli listesinde yer alan yapıya yılda 6 milyon ziyaretçi gelir.', latitude: 50.9413, longitude: 6.9583, address: 'Domkloster 4, Köln', rating: 4.8, reviewCount: 61000, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz (kule: 6 €)', openingHours: '06:00-21:00', tags: ['UNESCO', 'katedral', 'gotik', 'Ren', 'Köln'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1596020705668-a3a498e1b7fd?w=800&h=500&fit=crop' },
  // Dresden
  { countryCode: 'DE', cityName: 'Dresden', name: 'Zwinger Sarayı', slug: 'zwinger-sarayi-dresden', category: 'Tarihi', shortDescription: 'Barok mimarinin taç takdığı Elbe kıyısındaki saray.', description: 'Zwinger, 1709-1728 yılları arasında Augustus II döneminde inşa edilmiş muhteşem bir Barok saray kompleksidir. İçinde Rüstkammer (silah zırhı koleksiyonu), Porselain Kabinesi ve Eski Ustalar Galeri Galerisi\'nin yanı sıra büyüleyici bir iç bahçe bulunmaktadır. Dünya Savaşı II\'de tahrip edilen ve kapsamlı restorasyonla yeniden hayata kavuşturulan Zwinger, günümüzde Dresden\'in en önemli müze kompleksidir.', latitude: 51.0534, longitude: 13.7347, address: 'Theaterplatz 1, Dresden', rating: 4.7, reviewCount: 29000, visitDuration: '2-3 saat', entranceFee: '14 €', openingHours: '10:00-18:00 (Salı kapalı)', tags: ['barok', 'saray', 'müze', 'galeri', 'Elbe'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1564594327380-77e0e99a3c5d?w=800&h=500&fit=crop' },
  // Heidelberg
  { countryCode: 'DE', cityName: 'Heidelberg', name: 'Heidelberg Şatosu', slug: 'heidelberg-satosu', category: 'Tarihi', shortDescription: 'Dünya\'nın en büyük şarap fıçısına ev sahipliği yapan romantik rönesans şatosu.', description: 'Heidelberg Şatosu, Almanya\'nın en ünlü yıkık şatolarından biridir. Neckar Nehri üzerindeki tepede yükselen şato, Alman romantizminin ve tarihinin bütünleşik bir parçasıdır. 220.000 litre kapasiteliyle dünyanın en büyük şarap fıçısına ev sahipliği yapar. Eski şehir ve Neckar nehriyle birlikte Heidelberg\'e gerçekten masalsı bir atmosfer kazandırır.', latitude: 49.4097, longitude: 8.7143, address: 'Schlosshof 1, Heidelberg', rating: 4.7, reviewCount: 34000, visitDuration: '2-3 saat', entranceFee: '6 €', openingHours: '10:00-18:00', tags: ['şato', 'rönesans', 'şarap', 'manzara', 'tarihi'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&h=500&fit=crop' },
];

// ────────────────────────────────────────────────
// SEEDER FUNCTION
// ────────────────────────────────────────────────

const allForeignPlaces = [
  ...italyPlaces,
  ...japanPlaces,
  ...francePlaces,
  ...spainPlaces,
  ...brazilPlaces,
  ...egyptPlaces,
  ...australiaPlaces,
  ...germanyPlaces,
];

const seedForeignPlaces = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('MongoDB Bağlandı');

    // Türkiye dışındaki ülkeleri bul
    const countries = await Country.find({ code: { $ne: 'TR' } });
    const countryMap = {};
    countries.forEach(c => { countryMap[c.code] = c._id; });

    console.log(`Bulunan ülkeler: ${countries.map(c => c.code).join(', ')}`);

    // Tüm yabancı şehirleri al
    const allCities = await City.find({ country: { $in: countries.map(c => c._id) } });
    // city lookup: countryId + cityName -> cityId
    const cityMap = {};
    allCities.forEach(city => {
      const key = `${city.country.toString()}__${city.name}`;
      cityMap[key] = city._id;
    });

    let addedCount = 0;
    let skippedCount = 0;

    for (const placeData of allForeignPlaces) {
      const countryId = countryMap[placeData.countryCode];
      if (!countryId) {
        console.warn(`⚠️  Ülke bulunamadı: ${placeData.countryCode} — atlandı`);
        skippedCount++;
        continue;
      }

      const key = `${countryId.toString()}__${placeData.cityName}`;
      const cityId = cityMap[key];
      if (!cityId) {
        console.warn(`⚠️  Şehir bulunamadı: ${placeData.cityName} (${placeData.countryCode}) — atlandı`);
        skippedCount++;
        continue;
      }

      const { countryCode, cityName, ...placeFields } = placeData;

      // Slug zaten varsa atla
      const existing = await Place.findOne({ slug: placeFields.slug });
      if (existing) {
        console.log(`⏭️  Zaten mevcut: ${placeFields.name}`);
        skippedCount++;
        continue;
      }

      await Place.create({
        ...placeFields,
        city: cityId,
        country: countryId,
      });

      console.log(`✅ [${placeData.countryCode}] ${placeData.cityName} - ${placeData.name}`);
      addedCount++;
    }

    console.log(`\n🎉 ${addedCount} yer başarıyla eklendi! (${skippedCount} atlandı)`);

    await mongoose.connection.close();
    console.log('Veritabanı bağlantısı kapatıldı');
    process.exit(0);
  } catch (err) {
    console.error('Seed hatası:', err.message);
    process.exit(1);
  }
};

seedForeignPlaces();
