require('dotenv').config();
const mongoose = require('mongoose');
const Place = require('../models/Place');
const City = require('../models/City');
const Country = require('../models/Country');

const MONGO_URI = process.env.MONGO_URI;

// Türkiye'nin öne çıkan turistik yerleri
const placesData = [
  // İstanbul
  { cityName: 'İstanbul', name: 'Ayasofya', slug: 'ayasofya', category: 'Tarihi', shortDescription: 'Bizans döneminden kalma dünyaca ünlü yapı.', description: 'MS 537 yılında inşa edilen Ayasofya, önce Hristiyan bazilikası, sonra cami, ardından müze ve şimdi tekrar cami olarak hizmet veren eşsiz bir yapıdır. UNESCO Dünya Mirası listesinde yer alır. Muhteşem kubbesi, mozaikleri ve mimari ihtişamıyla dünyanın en önemli yapılarından biridir.', latitude: 41.0086, longitude: 28.9802, address: 'Sultan Ahmet, Ayasofya Meydanı, Fatih/İstanbul', rating: 4.8, reviewCount: 45230, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat (namaz vakitleri hariç)', tags: ['UNESCO', 'mimari', 'tarih', 'Bizans', 'Osmanlı'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800&h=500&fit=crop' },
  { cityName: 'İstanbul', name: 'Topkapı Sarayı', slug: 'topkapi-sarayi', category: 'Müze', shortDescription: 'Osmanlı padişahlarının yüzyıllarca yaşadığı saray.', description: 'Topkapı Sarayı, 1478-1856 yılları arasında Osmanlı padişahlarının resmi ikametgahı ve yönetim merkezi olarak kullanılmıştır. Saray, Harem bölümü, dört avlu, hazine odaları ve kutsal emanetler koleksiyonu ile ziyaretçilerini büyüler. UNESCO Dünya Mirası listesindedir.', latitude: 41.0115, longitude: 28.9833, address: 'Cankurtaran, 34122 Fatih/İstanbul', rating: 4.7, reviewCount: 38500, visitDuration: '2-3 saat', entranceFee: '320 TL', openingHours: '09:00-18:00 (Salı kapalı)', tags: ['UNESCO', 'saray', 'Osmanlı', 'müze', 'hazine'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1564594327380-77e0e99a3c5d?w=800&h=500&fit=crop' },
  { cityName: 'İstanbul', name: 'Kapalıçarşı', slug: 'kapalicarsi', category: 'Alışveriş', shortDescription: 'Dünyanın en eski ve büyük kapalı çarşılarından.', description: 'Kapalıçarşı, 1461 yılında Fatih Sultan Mehmet döneminde inşa edilmiştir. 61 cadde ve 3.000\'den fazla dükkan barındıran çarşı, altın, mücevher, halı, seramik ve baharat gibi ürünlerin satıldığı devasa bir alışveriş merkezidir. Günde yaklaşık 400.000 ziyaretçi ağırlar.', latitude: 41.0108, longitude: 28.9680, address: 'Beyazıt, 34126 Fatih/İstanbul', rating: 4.5, reviewCount: 29800, visitDuration: '2-4 saat', entranceFee: 'Ücretsiz', openingHours: '08:30-19:00 (Pazar kapalı)', tags: ['alışveriş', 'tarih', 'hediyelik', 'kültür'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1555217851-6141535bd771?w=800&h=500&fit=crop' },
  { cityName: 'İstanbul', name: 'Galata Kulesi', slug: 'galata-kulesi', category: 'Tarihi', shortDescription: 'İstanbul silüetinin simgesi olan ortaçağ kulesi.', description: 'Galata Kulesi, 1348 yılında Cenevizliler tarafından inşa edilen 67 metre yüksekliğindeki kuledir. İstanbul Boğazı, Haliç ve tarihi yarımadanın panoramik manzarasını sunar. Kule, yüzyıllar boyunca gözetleme kulesi, yangın gözetleme kulesi ve hapishane olarak kullanılmıştır.', latitude: 41.0256, longitude: 28.9741, address: 'Bereketzade, Galata Kulesi, Beyoğlu/İstanbul', rating: 4.6, reviewCount: 22100, visitDuration: '30-60 dk', entranceFee: '130 TL', openingHours: '08:30-22:00', tags: ['manzara', 'kule', 'panorama', 'fotoğraf'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1621367538757-fcdb5de6eab0?w=800&h=500&fit=crop' },
  { cityName: 'İstanbul', name: 'Yerebatan Sarnıcı', slug: 'yerebatan-sarnici', category: 'Tarihi', shortDescription: 'Bizans döneminden kalma yeraltı su sarnıcı.', description: 'Yerebatan Sarnıcı, MS 532 yılında İmparator I. Justinianus tarafından yaptırılmıştır. 336 sütunun taşıdığı bu yeraltı yapısı, 80.000 metreküp su depolama kapasitesine sahiptir. Medusa başı kabartmalı sütunları ile ünlüdür. Atmosferik aydınlatması ve su yüzeyindeki yansımalarıyla büyüleyici bir deneyim sunar.', latitude: 41.0084, longitude: 28.9779, address: 'Alemdar, Yerebatan Cd. 1/3, Fatih/İstanbul', rating: 4.6, reviewCount: 19500, visitDuration: '30-45 dk', entranceFee: '190 TL', openingHours: '09:00-19:00', tags: ['Bizans', 'yeraltı', 'sarnıç', 'tarih', 'mimari'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1616419805715-7bfa32894206?w=800&h=500&fit=crop' },

  // Ankara
  { cityName: 'Ankara', name: 'Anıtkabir', slug: 'anitkabir', category: 'Müze', shortDescription: 'Atatürk\'ün anıt mezarı ve müzesi.', description: 'Anıtkabir, Türkiye Cumhuriyeti\'nin kurucusu Mustafa Kemal Atatürk\'ün anıt mezarıdır. 1944-1953 yılları arasında inşa edilen yapı, Aslanlı Yol, Tören Alanı, Atatürk Müzesi ve çeşitli anıtlardan oluşur. Her yıl milyonlarca kişi tarafından ziyaret edilen Anıtkabir, Türkiye\'nin en önemli simgelerinden biridir.', latitude: 39.9254, longitude: 32.8369, address: 'Yücetepe, Akdeniz Cd., Çankaya/Ankara', rating: 4.9, reviewCount: 52000, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '09:00-17:00', tags: ['Atatürk', 'müze', 'anıt', 'tarih', 'cumhuriyet'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1590076083190-ef0edd1ef7a0?w=800&h=500&fit=crop' },
  { cityName: 'Ankara', name: 'Ankara Kalesi', slug: 'ankara-kalesi', category: 'Tarihi', shortDescription: 'Ankara\'nın tarihi kalbi ve panoramik manzara noktası.', description: 'Ankara Kalesi, şehrin en eski yerleşim yeridir. Hitit, Roma, Bizans ve Osmanlı dönemlerinden izler taşır. Kalenin içinde geleneksel Ankara evleri, restoranlar ve hediyelik eşya dükkanları bulunur. Kale surlarından Ankara\'nın panoramik manzarası izlenebilir.', latitude: 39.9408, longitude: 32.8644, address: 'Kale, 06240 Altındağ/Ankara', rating: 4.4, reviewCount: 11200, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['kale', 'manzara', 'tarih', 'Osmanlı'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1631560169992-20d8e5f3a7eb?w=800&h=500&fit=crop' },

  // Antalya
  { cityName: 'Antalya', name: 'Kaleiçi', slug: 'kaleici-antalya', category: 'Tarihi', shortDescription: 'Antalya\'nın tarihi kalbi, restore edilmiş Osmanlı evleri.', description: 'Kaleiçi, Antalya\'nın tarihi şehir merkezidir. Roma, Bizans, Selçuklu ve Osmanlı dönemlerinden kalma yapılarla dolu dar sokakları, butik otelleri, restoranları ve hediyelik eşya dükkanlarıyla büyüleyici bir atmosfer sunar. Hadrian Kapısı, Yivli Minare ve tarihi liman başlıca görülecek yerlerdir.', latitude: 36.8841, longitude: 30.7056, address: 'Kaleiçi, Muratpaşa/Antalya', rating: 4.7, reviewCount: 18900, visitDuration: '2-3 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['tarih', 'mimari', 'Osmanlı', 'Roma', 'sahil'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1593238739364-18cfde865990?w=800&h=500&fit=crop' },
  { cityName: 'Antalya', name: 'Düden Şelalesi', slug: 'duden-selalesi', category: 'Doğa', shortDescription: 'Denize dökülen muhteşem şelale.', description: 'Düden Şelalesi, Antalya\'nın en popüler doğal güzelliklerinden biridir. Alt Düden (Karpuzkaldıran) şelalesi 40 metre yükseklikten Akdeniz\'e dökülür. Çevresindeki park alanı piknik ve yürüyüş için idealdir. Tekne turlarıyla denizden şelaleyi izlemek de mümkündür.', latitude: 36.8517, longitude: 30.7889, address: 'Çağlayan, Lara Cd., Muratpaşa/Antalya', rating: 4.5, reviewCount: 14200, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['şelale', 'doğa', 'fotoğraf', 'park'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=500&fit=crop' },
  { cityName: 'Antalya', name: 'Aspendos Antik Tiyatrosu', slug: 'aspendos-antik-tiyatrosu', category: 'Tarihi', shortDescription: 'Dünyanın en iyi korunmuş Roma tiyatrosu.', description: 'Aspendos Antik Tiyatrosu, MS 2. yüzyılda Roma İmparatoru Marcus Aurelius döneminde inşa edilmiştir. 15.000-20.000 kişilik kapasitesiyle dünyanın en iyi korunmuş antik tiyatrolarından biridir. Akustiği o kadar mükemmeldir ki sahnenin ortasında düşürülen bir madeni para en üst sıradan duyulabilir.', latitude: 36.9389, longitude: 31.1722, address: 'Aspendos, Serik/Antalya', rating: 4.7, reviewCount: 8900, visitDuration: '1-2 saat', entranceFee: '90 TL', openingHours: '08:00-19:00', tags: ['Roma', 'tiyatro', 'antik', 'mimari', 'akustik'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1569949381669-ecf31ae8f613?w=800&h=500&fit=crop' },

  // Nevşehir (Kapadokya)
  { cityName: 'Nevşehir', name: 'Göreme Açık Hava Müzesi', slug: 'goreme-acik-hava-muzesi', category: 'Müze', shortDescription: 'Kapadokya\'nın kalbinde UNESCO Dünya Mirası.', description: 'Göreme Açık Hava Müzesi, kayalara oyulmuş kiliseleri, şapelleri ve freskleriyle ünlüdür. MS 10-12. yüzyıllardan kalma kiliseler, Hristiyanlık tarihinin en önemli örneklerinden bazılarını barındırır. Karanlık Kilise, Elmalı Kilise ve Yılanlı Kilise en bilinen yapılarıdır. UNESCO Dünya Mirası listesindedir.', latitude: 38.6431, longitude: 34.8310, address: 'Göreme, 50180 Nevşehir', rating: 4.8, reviewCount: 21300, visitDuration: '2-3 saat', entranceFee: '150 TL', openingHours: '08:00-19:00', tags: ['UNESCO', 'Kapadokya', 'kilise', 'fresk', 'peri bacası'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?w=800&h=500&fit=crop' },
  { cityName: 'Nevşehir', name: 'Derinkuyu Yeraltı Şehri', slug: 'derinkuyu-yeralti-sehri', category: 'Tarihi', shortDescription: 'Dünyanın en derin ve büyük yeraltı şehri.', description: 'Derinkuyu Yeraltı Şehri, 85 metre derinlikte 8 kat aşağıya inen devasa bir yeraltı kompleksidir. Yaklaşık 20.000 kişiyi barındırabilecek kapasitedeki şehirde yaşam alanları, kiliseler, ahırlar, şarap imalathaneleri ve havalandırma şaftları bulunur. MÖ 8. yüzyılda Frigler tarafından inşa edilmeye başlanmıştır.', latitude: 38.3733, longitude: 34.7344, address: 'Derinkuyu, 50700 Nevşehir', rating: 4.6, reviewCount: 12800, visitDuration: '1-2 saat', entranceFee: '120 TL', openingHours: '08:00-19:00', tags: ['yeraltı', 'tarih', 'Kapadokya', 'macera', 'arkeoloji'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1625231952690-e0dba91e60b2?w=800&h=500&fit=crop' },

  // İzmir
  { cityName: 'İzmir', name: 'Efes Antik Kenti', slug: 'efes-antik-kenti', category: 'Tarihi', shortDescription: 'Antik dünyanın en iyi korunmuş şehirlerinden.', description: 'Efes Antik Kenti, MÖ 6000\'li yıllardan itibaren yerleşim görmüş, antik dünyanın en büyük ve en iyi korunmuş şehirlerinden biridir. Celsus Kütüphanesi, Büyük Tiyatro, Hadrian Tapınağı ve terasevleri ile ünlüdür. Dünyanın yedi harikasından biri olan Artemis Tapınağı\'nın kalıntıları yakınındadır. UNESCO Dünya Mirası listesindedir.', latitude: 37.9395, longitude: 27.3419, address: 'Efes Harabeleri, Selçuk/İzmir', rating: 4.8, reviewCount: 35200, visitDuration: '3-4 saat', entranceFee: '200 TL', openingHours: '08:00-19:00', tags: ['UNESCO', 'Roma', 'antik kent', 'arkeoloji', 'kütüphane'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1590076215667-875c2717b81e?w=800&h=500&fit=crop' },

  // Denizli
  { cityName: 'Denizli', name: 'Pamukkale Travertenleri', slug: 'pamukkale-travertenleri', category: 'Doğa', shortDescription: 'Beyaz travertenleriyle dünyaca ünlü doğa harikası.', description: 'Pamukkale (Pamuk Kalesi) travertenleri, termal suların yüzyıllar boyunca oluşturduğu bembeyaz kireç taşı teraslarıdır. Hierapolis Antik Kenti ile birlikte UNESCO Dünya Mirası listesinde yer alır. Stratonikeia kapısından başlayan yürüyüş parkuru, antik havuz ve travertenlerin panoramik manzarası unutulmaz bir deneyim sunar.', latitude: 37.9204, longitude: 29.1187, address: 'Pamukkale, 20280 Denizli', rating: 4.7, reviewCount: 28700, visitDuration: '3-5 saat', entranceFee: '110 TL', openingHours: '06:30-21:00', tags: ['UNESCO', 'doğa', 'termal', 'traverten', 'antik'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1600460249295-bf99de4e3db3?w=800&h=500&fit=crop' },

  // Çanakkale
  { cityName: 'Çanakkale', name: 'Truva Antik Kenti', slug: 'truva-antik-kenti', category: 'Tarihi', shortDescription: 'Efsanevi Truva Savaşı\'nın yaşandığı antik kent.', description: 'Truva Antik Kenti, Homeros\'un İlyada destanında anlattığı efsanevi Truva Savaşı\'nın geçtiği yerdir. MÖ 3000-MS 500 arasında 9 farklı yerleşim katmanı bulunur. UNESCO Dünya Mirası listesindedir. Girişte yer alan tahta Truva Atı replikası en popüler fotoğraf noktasıdır.', latitude: 39.9575, longitude: 26.2389, address: 'Tevfikiye, 17100 Çanakkale', rating: 4.3, reviewCount: 9800, visitDuration: '1-2 saat', entranceFee: '100 TL', openingHours: '08:00-19:00', tags: ['UNESCO', 'antik kent', 'arkeoloji', 'Truva', 'mitoloji'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1614531341773-3bff8b7cb3fc?w=800&h=500&fit=crop' },

  // Konya
  { cityName: 'Konya', name: 'Mevlana Müzesi', slug: 'mevlana-muzesi', category: 'Müze', shortDescription: 'Hz. Mevlana\'nın türbesi ve dergahı.', description: 'Mevlana Müzesi, büyük düşünür ve mutasavvıf Mevlana Celaleddin Rumi\'nin türbesini barındıran dergahtır. Yeşil kubbesiyle Konya\'nın simgesidir. Müzede Mevlana\'ya ait eserler, el yazması Mesnevi nüshaları, sema kıyafetleri ve tarihi eşyalar sergilenir. Türkiye\'nin en çok ziyaret edilen müzelerinden biridir.', latitude: 37.8714, longitude: 32.5054, address: 'Aziziye, Mevlana Cd., Karatay/Konya', rating: 4.8, reviewCount: 32100, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '09:00-18:30', tags: ['Mevlana', 'müze', 'tasavvuf', 'sema', 'kültür'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1609861637806-01011a9b0df7?w=800&h=500&fit=crop' },

  // Trabzon
  { cityName: 'Trabzon', name: 'Sümela Manastırı', slug: 'sumela-manastiri', category: 'Tarihi', shortDescription: 'Altındere Vadisi\'nde kayalara oyulmuş manastır.', description: 'Sümela Manastırı (Meryem Ana Manastırı), Trabzon\'un Maçka ilçesinde Altındere Vadisi Milli Parkı içinde, 300 metre yükseklikteki sarp kayalıklara inşa edilmiştir. MS 386 yılında kurulan manastır, freskleri ve dramatik konumuyla büyüler. 2010\'dan itibaren kapsamlı restorasyondan geçmiştir.', latitude: 40.6906, longitude: 39.6568, address: 'Altındere Vadisi, Maçka/Trabzon', rating: 4.7, reviewCount: 15600, visitDuration: '2-3 saat', entranceFee: '60 TL', openingHours: '08:00-18:00', tags: ['manastır', 'Bizans', 'doğa', 'tarih', 'fresk'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1590603639781-49e8b34f17d0?w=800&h=500&fit=crop' },

  // Muğla
  { cityName: 'Muğla', name: 'Ölüdeniz', slug: 'oludeniz', category: 'Plaj', shortDescription: 'Türkiye\'nin en ünlü plajı ve yamaç paraşütü merkezi.', description: 'Ölüdeniz, turkuaz rengi suları ve beyaz kumlu plajıyla dünyaca ünlü bir tatil beldesdir. Blue Lagoon (Mavi Deniz) tabiat parkı korunan doğal bir lagündür. Babadağ\'dan yamaç paraşütüyle uçuş yaparak eşsiz manzarayı kuşbakışı izleyebilirsiniz. Likya Yolu yürüyüşünün başlangıç noktasıdır.', latitude: 36.5494, longitude: 29.1153, address: 'Ölüdeniz, Fethiye/Muğla', rating: 4.8, reviewCount: 24500, visitDuration: 'Tam gün', entranceFee: '32 TL (Tabiat Parkı)', openingHours: '08:00-20:00', tags: ['plaj', 'yamaç paraşütü', 'lagün', 'doğa', 'deniz'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=800&h=500&fit=crop' },

  // Mardin
  { cityName: 'Mardin', name: 'Mardin Taş Evleri', slug: 'mardin-tas-evleri', category: 'Tarihi', shortDescription: 'Mezopotamya ovasına bakan eşsiz taş mimari.', description: 'Mardin\'in tarihi taş evleri, kentin eşsiz siluetini oluşturur. Kireç taşından yapılmış bu evler, Mezopotamya ovasına hakim bir tepenin yamacına sıralanmıştır. Sokaklar arası geçitler, avlular ve teraslar Mardin mimarisinin karakteristik özellikleridir. Zinciriye Medresesi, Kasımiye Medresesi ve Deyrulzafaran Manastırı da mutlaka görülmelidir.', latitude: 37.3132, longitude: 40.7350, address: 'Eski Mardin, Artuklu/Mardin', rating: 4.6, reviewCount: 8400, visitDuration: '3-4 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['mimari', 'tarih', 'taş evler', 'Mezopotamya', 'kültür'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1589561454226-796a8c7e0c40?w=800&h=500&fit=crop' },

  // Gaziantep
  { cityName: 'Gaziantep', name: 'Zeugma Mozaik Müzesi', slug: 'zeugma-mozaik-muzesi', category: 'Müze', shortDescription: 'Dünyanın en büyük mozaik koleksiyonlarından biri.', description: 'Zeugma Mozaik Müzesi, Gaziantep\'in ve Türkiye\'nin en önemli müzelerinden biridir. Birecik Barajı suları altında kalan Zeugma antik kentinden kurtarılan Roma dönemi mozaikleri sergilenir. "Çingene Kızı" mozaiği müzenin en ünlü eseridir. 30.000 m² sergi alanıyla dünyanın en büyük mozaik müzesidir.', latitude: 37.0771, longitude: 37.3825, address: 'Mithatpaşa, Hacı Sani Konukoğlu Blv., Şehitkamil/Gaziantep', rating: 4.7, reviewCount: 11900, visitDuration: '2-3 saat', entranceFee: '60 TL', openingHours: '09:00-19:00', tags: ['mozaik', 'müze', 'Roma', 'arkeoloji', 'Çingene Kızı'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1590074073580-fd55ce07cd8c?w=800&h=500&fit=crop' },

  // Şanlıurfa
  { cityName: 'Şanlıurfa', name: 'Göbeklitepe', slug: 'gobeklitepe', category: 'Tarihi', shortDescription: 'Dünyanın bilinen en eski tapınak alanı.', description: 'Göbeklitepe, MÖ 10.000 yılına (yaklaşık 12.000 yıl öncesine) tarihlenen dünyanın bilinen en eski tapınak alanıdır. Neolitik dönemde inşa edilmiş T biçimli dikili taşlar, üzerlerindeki hayvan kabartmaları ve geometrik motiflerle insanlık tarihinin en büyük keşiflerinden biri kabul edilir. UNESCO Dünya Mirası listesindedir.', latitude: 37.2233, longitude: 38.9225, address: 'Örencik, 63290 Haliliye/Şanlıurfa', rating: 4.8, reviewCount: 9200, visitDuration: '1-2 saat', entranceFee: '60 TL', openingHours: '08:00-19:00', tags: ['UNESCO', 'Neolitik', 'arkeoloji', 'tarih', 'tapınak'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1654473741316-77b2c771a237?w=800&h=500&fit=crop' },

  // Bursa
  { cityName: 'Bursa', name: 'Uludağ Milli Parkı', slug: 'uludag-milli-parki', category: 'Doğa', shortDescription: 'Türkiye\'nin en popüler kış sporları merkezi.', description: 'Uludağ, 2.543 metre yüksekliğiyle Marmara Bölgesi\'nin en yüksek dağıdır. Kış aylarında kayak ve snowboard, yaz aylarında trekking ve doğa yürüyüşleri için ideal bir destinasyondur. Teleferik ile ulaşım mümkündür. Milli park statüsündeki alan zengin flora ve faunasıyla da dikkat çeker.', latitude: 40.0833, longitude: 29.2167, address: 'Uludağ Milli Parkı, 16370 Bursa', rating: 4.5, reviewCount: 18700, visitDuration: 'Tam gün', entranceFee: '30 TL (Araç girişi)', openingHours: '24 saat', tags: ['kayak', 'doğa', 'kış sporları', 'trekking', 'teleferik'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?w=800&h=500&fit=crop' },
  { cityName: 'Bursa', name: 'Ulu Cami', slug: 'ulu-cami-bursa', category: 'Tarihi', shortDescription: 'Osmanlı mimarisinin şaheseri, 20 kubbeli büyük cami.', description: 'Bursa Ulu Camii, Sultan I. Bayezid tarafından 1399 yılında yaptırılmış, Osmanlı mimarisinin en önemli örneklerinden biridir. 20 kubbesiyle dikkat çeken caminin içindeki şadırvan, mihrap ve kûfi hattı ile yazılmış Ayet\'el Kürsî en büyük hat yazısına sahiptir. Bursa\'nın simgesi olan yapı tarihi şehir merkezindedir.', latitude: 40.1838, longitude: 29.0611, address: 'Ulucami Mh., Atatürk Cd., Osmangazi/Bursa', rating: 4.9, reviewCount: 24300, visitDuration: '30-60 dk', entranceFee: 'Ücretsiz', openingHours: 'Namaz vakitleri', tags: ['cami', 'Osmanlı', 'mimari', 'hattı', 'tarihi'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1597737419973-3a9b66efe6e8?w=800&h=500&fit=crop' },
  { cityName: 'Bursa', name: 'Bursa Kapalı Çarşı', slug: 'bursa-kapali-carsi', category: 'Alışveriş', shortDescription: 'Osmanlı döneminden kalma tarihi bedesten ve çarşı.', description: 'Bursa Kapalı Çarşı (Bedesten), 15. yüzyılda inşa edilmiş tarihi bir ticaret merkezidir. İpek, mücevher, antika ve geleneksel el işi ürünlerin satıldığı dükkanlarıyla Bursa\'nın ticaret tarihinin canlı bir parçasıdır. Koza Han ile birlikte şehrin en önemli tarihi çarşısını oluşturur.', latitude: 40.1840, longitude: 29.0595, address: 'Kapalıçarşı, Osmangazi/Bursa', rating: 4.4, reviewCount: 9800, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '09:00-19:00 (Pazar kapalı)', tags: ['alışveriş', 'tarihi', 'Osmanlı', 'ipek', 'zanaat'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1555217851-6141535bd771?w=800&h=500&fit=crop' },

  // Edirne
  { cityName: 'Edirne', name: 'Selimiye Camii', slug: 'selimiye-camii', category: 'Tarihi', shortDescription: 'Mimar Sinan\'ın şaheseri, UNESCO Dünya Mirası.', description: 'Selimiye Camii, Osmanlı mimarisi\'nin zirvesi kabul edilen ve Mimar Sinan tarafından "en güzel eserim" olarak nitelendirilen yapıdır. 1574 yılında tamamlanan cami, 71 metre yüksekliğindeki dört minaresi ve 31.25 metre çapındaki dev kubbesiyle Süleymaniye\'yi bile geride bırakır. UNESCO Dünya Mirası listesindedir.', latitude: 41.6761, longitude: 26.5557, address: 'Selimiye, Mimar Sinan Cd., Edirne Merkez/Edirne', rating: 4.9, reviewCount: 19800, visitDuration: '1-2 saat', entranceFee: 'Ücretsiz', openingHours: '09:00-18:00', tags: ['UNESCO', 'Mimar Sinan', 'Osmanlı', 'cami', 'mimari'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1589185152600-26d2d0aa0cd5?w=800&h=500&fit=crop' },
  { cityName: 'Edirne', name: 'Kırkpınar Yağlı Güreş Alanı', slug: 'kirkpinar-yagli-gures', category: 'Kültür', shortDescription: 'Dünyanın en eski spor organizasyonu.', description: 'Kırkpınar Yağlı Güreşleri, 1346 yılından bu yana kesintisiz düzenlenen dünyanın en eski spor organizasyonudur. UNESCO Somut Olmayan Kültürel Miras listesinde yer alır. Her yıl Temmuz ayında Sarayiçi alanında düzenlenen bu festival, yüzlerce "pehlivan"ı bir araya getirir. Türk geleneksel kültürünün en önemli parçalarından biridir.', latitude: 41.6956, longitude: 26.5597, address: 'Sarayiçi, Edirne', rating: 4.7, reviewCount: 6200, visitDuration: '3-4 saat (etkinlik günleri)', entranceFee: 'Değişken', openingHours: 'Etkinlik takvimi', tags: ['UNESCO', 'güreş', 'kültür', 'gelenek', 'spor'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&h=500&fit=crop' },

  // Karabük (Safranbolu)
  { cityName: 'Karabük', name: 'Safranbolu Tarihi Çarşı', slug: 'safranbolu-tarihi-carsi', category: 'Tarihi', shortDescription: 'UNESCO korumasındaki Osmanlı çarşı kültürünün son örneği.', description: 'Safranbolu, Osmanlı dönemi konaklarını, çarşısını ve geleneksel mimarisini olağanüstü biçimde korumuş bir şehirdir. 1994\'te UNESCO Dünya Mirası listesine alınan şehir, birbirinden güzel ahşap konakları, taş hanları ve tarihi çarşısıyla zaman yolculuğuna çıkarır. Safranbolu\'nun lokomu ve safranı da meşhurdur.', latitude: 41.2534, longitude: 32.6906, address: 'Çarşı Mh., Karabük', rating: 4.8, reviewCount: 21500, visitDuration: '1 gün', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['UNESCO', 'Osmanlı', 'konak', 'mimari', 'kültür'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1598887142930-f1e0c8a8c4f1?w=800&h=500&fit=crop' },
  { cityName: 'Karabük', name: 'Yörük Köyü', slug: 'yoruk-koyu-safranbolu', category: 'Kültür', shortDescription: 'Geleneksel Türk köy yaşamının yaşayan müzesi.', description: 'Safranbolu\'ya bağlı Yörük Köyü, 200 yıllık geçmişiyle geleneksel Türk köy mimarisini ve yaşamını günümüze taşıyan özgün bir yerleşimdir. Ahşap evler, taş fırınlar ve köy kahvesi ile otantik bir Anadolu deneyimi sunar. Çevre yürüyüş yolları ve manzarası ile de ünlüdür.', latitude: 41.2786, longitude: 32.7456, address: 'Yörük Köyü, Karabük', rating: 4.5, reviewCount: 4800, visitDuration: '2-3 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['köy', 'kültür', 'mimari', 'doğa', 'geleneksel'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&h=500&fit=crop' },

  // Kars
  { cityName: 'Kars', name: 'Ani Harabeleri', slug: 'ani-harabeleri', category: 'Tarihi', shortDescription: 'Bin yıllık kayıp şehir, Orta Çağ\'ın unutulmuş başkenti.', description: 'Ani, 10-11. yüzyıllarda Ermeni Bagratid Krallığı\'nın başkenti olmuş ve zamanın en büyük şehirlerinden biri olarak 100.000\'i aşkın nüfusu barındırmıştır. Günümüzde yalnızca etkileyici kalıntıları ayakta olan bu "kayıp şehir" UNESCO Dünya Mirası listesindedir. Katedral, kiliseler, saraylar ve surlarıyla muhteşem bir manzara sunar.', latitude: 40.5063, longitude: 43.5707, address: 'Ani, Ocaklı Köyü, Kars', rating: 4.7, reviewCount: 8900, visitDuration: '2-3 saat', entranceFee: '75 TL', openingHours: '08:00-19:00', tags: ['UNESCO', 'antik kent', 'Ermeni', 'tarih', 'arkeoloji'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1619265413490-4e33bff7dab3?w=800&h=500&fit=crop' },
  { cityName: 'Kars', name: 'Çıldır Gölü', slug: 'cildir-golu', category: 'Doğa', shortDescription: 'Kışın buz üstünde atlı kızak gezisinin adresi.', description: 'Çıldır Gölü, Türkiye\'nin 3. büyük gölüdür ve deniz seviyesinden 1.959 metre yükseklikte yer alır. Kış aylarında tamamen donan gölde yapılan atlı kızak ve ata binerek buz üzerinde gezinti, bölgeye özgü eşsiz bir deneyim sunar. Yaz aylarında ise balıkçılık ve kamp için mükemmel bir ortam oluşturur.', latitude: 41.0667, longitude: 43.2333, address: 'Çıldır, Ardahan', rating: 4.6, reviewCount: 5400, visitDuration: 'Yarım - Tam gün', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['göl', 'kış', 'kızak', 'doğa', 'fotoğraf'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1491555103944-7c647fd857e6?w=800&h=500&fit=crop' },

  // Van
  { cityName: 'Van', name: 'Van Kalesi', slug: 'van-kalesi', category: 'Tarihi', shortDescription: 'Göl kenarında yükselen 3000 yıllık Urartu kalesi.', description: 'Van Kalesi, Urartu döneminden (MÖ 9. yüzyıl) kalma devasa bir kaya kalesidir. Van Gölü\'nün kıyısında 100 metre yüksekliğindeki uçurumların üzerine inşa edilmiş olan kale, kaya mezarlarını, yazıtları ve muhteşem göl manzarasını barındırır. Kalesinin altındaki Eski Van şehir harabasıyla birlikte ziyaret önerilir.', latitude: 38.5020, longitude: 43.3404, address: 'Van Kalesi, Tuşba/Van', rating: 4.6, reviewCount: 9700, visitDuration: '1-2 saat', entranceFee: '40 TL', openingHours: '08:00-19:00', tags: ['Urartu', 'kale', 'tarih', 'göl manzarası', 'arkeoloji'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1531761796027-b2df8e26a94b?w=800&h=500&fit=crop' },
  { cityName: 'Van', name: 'Akdamar Kilisesi', slug: 'akdamar-kilisesi', category: 'Tarihi', shortDescription: 'Van Gölü\'ndeki adada 10. yüzyıl Ermeni kilisesi.', description: 'Akdamar Kilisesi (Kutsal Haç Kilisesi), Van Gölü\'ndeki Akdamar Adası\'nda 921 yılında inşa edilmiştir. Dış cephesindeki İncil sahnelerini anlatan eşsiz kabartma işlemeleriyle ünlüdür. Adaya tekneyle ulaşılır; ada üzerinde güzel yürüyüş yolları ve badem bahçeleri mevcuttur. Türkiye\'nin en özgün dini yapılarından biridir.', latitude: 38.3472, longitude: 43.0442, address: 'Akdamar Adası, Van Gölü, Gevaş/Van', rating: 4.8, reviewCount: 11300, visitDuration: '1-2 saat (tekne dahil)', entranceFee: '50 TL (tekne)', openingHours: '09:00-18:00', tags: ['kilise', 'ada', 'göl', 'Ermeni', 'tarih'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop' },

  // Eskişehir
  { cityName: 'Eskişehir', name: 'Odunpazarı Tarihi Mahallesi', slug: 'odunpazari-tarihi-mahallesi', category: 'Tarihi', shortDescription: 'Renkli Osmanlı evleri ve Avrupa atmosferi.', description: 'Odunpazarı, Eskişehir\'in tarihi semtidir. Rengarenk restore edilmiş Osmanlı dönemi ahşap evleri, köprüler, kanallar ve cafe-barlarla dolu dokusu ile şehre Avrupa havasını katan bir bölgedir. Gondollerin gezdiği kanallar, seramik ve ebru atölyeleri, Modern Müze Odunpazarı (MODERN) ile sanat, kültür ve tarihin iç içe geçtiği bir destinasyon.', latitude: 39.7781, longitude: 30.5289, address: 'Odunpazarı, Eskişehir', rating: 4.7, reviewCount: 16400, visitDuration: '2-4 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['tarihi', 'Osmanlı', 'kanal', 'kültür', 'sanat'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&h=500&fit=crop' },
  { cityName: 'Eskişehir', name: 'Porsuk Çayı Kıyısı', slug: 'porsuk-cayi-kiyisi', category: 'Doğa', shortDescription: 'Şehrin kalbinden geçen romantik nehir kıyısı.', description: 'Porsuk Çayı, Eskişehir\'in ortasından geçen ve şehre büyük bir canlılık katan nehirdir. Kıyı boyunca uzanan yürüyüş yolları, gondol turları, tekneler, kafeler ve parklar halkın en sevdiği buluşma noktalarıdır. Özellikle akşamları ışıklandırılan köprüler ve su yansımalarıyla romantik bir atmosfer yaratır.', latitude: 39.7740, longitude: 30.5197, address: 'Porsuk Bulvarı, Eskişehir', rating: 4.5, reviewCount: 12700, visitDuration: '1-3 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['nehir', 'gondol', 'yürüyüş', 'romantik', 'doğa'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&h=500&fit=crop' },

  // Diyarbakır
  { cityName: 'Diyarbakır', name: 'Diyarbakır Surları', slug: 'diyarbakir-surlari', category: 'Tarihi', shortDescription: 'UNESCO korumasındaki 5.5 km\'lik bazalt surlar.', description: 'Diyarbakır Surları, Çin Seddi\'nden sonra dünyanın en uzun bazalt surlarıdır. Romalılar, Bizanslılar, Emeviler, Abbasiler, Selçuklular ve Osmanlılar tarafından genişletilmiş olan surlar, Hevsel Bahçeleri ile birlikte 2015\'te UNESCO Dünya Mirası listesine girmiştir. 72 burç ve 4 büyük kapıdan oluşur.', latitude: 37.9255, longitude: 40.2297, address: 'Suriçi, Diyarbakır', rating: 4.7, reviewCount: 13500, visitDuration: '2-3 saat', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['UNESCO', 'surlar', 'bazalt', 'Osmanlı', 'Roma'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1580974852861-c381510bc98a?w=800&h=500&fit=crop' },
  { cityName: 'Diyarbakır', name: 'Büyük Kilise (Surp Giragos)', slug: 'surp-giragos-kilisesi', category: 'Tarihi', shortDescription: 'Türkiye\'nin en büyük Ermeni kilisesi.', description: 'Surp Giragos, ya da Diyarbakır\'daki Büyük Kilise, Türkiye\'nin en büyük ve dünyanın da önemli Ermeni Apostolik kiliselerinden biridir. 16. yüzyıla tarihlenen kilise, 2011-2012 yıllarında kapsamlı restorasyon geçirmiş ve yeniden ziyarete açılmıştır. Tarihi surların içinde yer alan kilise, mimari açıdan olağanüstü güzelliktedir.', latitude: 37.9241, longitude: 40.2278, address: 'Hasanpaşa Mh., Diyarbakır', rating: 4.5, reviewCount: 5700, visitDuration: '30-60 dk', entranceFee: 'Ücretsiz', openingHours: '09:00-18:00', tags: ['kilise', 'Ermeni', 'tarihi', 'mimari', 'suriçi'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1548625361-58a9d86b2a7b?w=800&h=500&fit=crop' },

  // Adıyaman
  { cityName: 'Adıyaman', name: 'Nemrut Dağı', slug: 'nemrut-dagi', category: 'Tarihi', shortDescription: 'Dev taş kafalar ve görkemli günbatımıyla dünyaca ünlü.', description: 'Nemrut Dağı, Kommagene Krallığı\'nın son hükümdarı Antiochos\'un emriyle MÖ 1. yüzyılda inşa edilmiş muazzam bir anıt mezardır. 2.134 metre yüksekliğindeki zirvede yer alan dev heykeller (Zeus, Apollon, Tyche ve heykel başları) UNESCO Dünya Mirası listesindedir. Gün doğumu ve gün batımında izlenmesi adeta büyülüdür.', latitude: 37.9808, longitude: 38.7414, address: 'Nemrut Dağı, Kahta/Adıyaman', rating: 4.8, reviewCount: 14700, visitDuration: '3-4 saat', entranceFee: '60 TL', openingHours: 'Gün doğumu-Gün batımı', tags: ['UNESCO', 'Kommagene', 'heykel', 'manzara', 'gün doğumu'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1616763777207-3d6e6e9e89f8?w=800&h=500&fit=crop' },

  // Rize
  { cityName: 'Rize', name: 'Uzungöl', slug: 'uzungol', category: 'Doğa', shortDescription: 'Karadeniz\'in masalsı dağ gölü ve yaylaları.', description: 'Uzungöl, Türkiye\'nin en güzel doğa destinasyonlarından biridir. Rize\'nin Çaykara ilçesine bağlı, 1090 metre rakımda yer alan bu küçük dağ gölü; çevreleyen sarp dağlar, yemyeşil ormanlar ve çiçekli yaylalarıyla masalsı bir manzara sunar. Özellikle Orta Doğu\'dan gelen turistler arasında büyük popülerliğe sahiptir.', latitude: 40.6136, longitude: 40.4236, address: 'Uzungöl, Çaykara/Rize', rating: 4.7, reviewCount: 19200, visitDuration: '1-2 gün', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['göl', 'yayla', 'doğa', 'Karadeniz', 'fotoğraf'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop' },
  { cityName: 'Rize', name: 'Ayder Yaylası', slug: 'ayder-yaylasi', category: 'Doğa', shortDescription: 'Kaçkar Dağları\'nın eteklerinde termal sulará sahip yayla.', description: 'Ayder Yaylası, Kaçkar Dağları Milli Parkı içinde denizden 1.350 metre yüksekliğinde yer alır. Şelaleleri, termal kaplıcaları, yeşil çayırları ve yöresel mimarisiyle büyüleyen Ayder, hem doğa tutkunları hem de dinlenmek isteyenler için ideal bir destinasyondur. Kaçkar Dağları\'na çıkan trekking güzergahlarının başlangıç noktasıdır.', latitude: 40.9270, longitude: 41.0434, address: 'Ayder, Çamlıhemşin/Rize', rating: 4.6, reviewCount: 11800, visitDuration: '1-3 gün', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['yayla', 'kaplıca', 'trekking', 'doğa', 'Kaçkar'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&h=500&fit=crop' },

  // Samsun
  { cityName: 'Samsun', name: 'Bandırma Vapuru Müzesi', slug: 'bandirma-vapuru-muzesi', category: 'Müze', shortDescription: 'Kurtuluş Savaşı\'nın başlangıcını simgeleyen tarihi vapur.', description: 'Bandırma Vapuru\'nun birebir replikası, Samsun Cumhuriyet Meydanı yakınında müze olarak ziyaretçilere açıktır. Atatürk\'ün 19 Mayıs 1919\'da Samsun\'a çıktığı geminin kopyası olan bu yapı, Türk Kurtuluş Savaşı\'nın sembolüdür. İçerisinde dönemin yaşam koşullarını gösteren sergiler yer almaktadır.', latitude: 41.2972, longitude: 36.3350, address: 'Kılıçdede Mh., Samsun', rating: 4.5, reviewCount: 7800, visitDuration: '30-60 dk', entranceFee: 'Ücretsiz', openingHours: '09:00-17:30', tags: ['müze', 'Atatürk', 'tarih', 'vapur', 'kurtuluş savaşı'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1569949381669-ecf31ae8f613?w=800&h=500&fit=crop' },

  // Amasya
  { cityName: 'Amasya', name: 'Amasya Kaya Mezarları', slug: 'amasya-kaya-mezarlari', category: 'Tarihi', shortDescription: 'Pontos krallığına ait kaya oymalı kraliyet mezarları.', description: 'Amasya Kaya Mezarları, MÖ 4-1. yüzyıllarda Pontos kraliyet ailesine ait kaya oymalı mezarlardır. Yeşilırmak\'a bakan sarp kayalıklara oyulmuş bu anıtsal yapılar, akşam aydınlatmasıyla son derece etkileyici bir görünüm kazanır. Amasya Kalesi\'yle birlikte şehrin en önemli simgelerini oluşturur.', latitude: 40.6539, longitude: 35.8352, address: 'Kızılırmak Mh., Merkez/Amasya', rating: 4.7, reviewCount: 9100, visitDuration: '1-2 saat', entranceFee: '40 TL', openingHours: '08:30-19:00', tags: ['Pontos', 'kaya mezarı', 'tarih', 'Yeşilırmak', 'manzara'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800&h=500&fit=crop' },

  // İzmir (Ek Yerler)
  { cityName: 'İzmir', name: 'Saat Kulesi ve Konak Meydanı', slug: 'izmir-saat-kulesi', category: 'Tarihi', shortDescription: 'İzmir\'in simgesi, 1901 yapımı tarihi saat kulesi.', description: 'İzmir Saat Kulesi, II. Abdülhamid\'in tahta çıkışının 25. yıldönümü için 1901\'de yaptırılmıştır. Levantın\'a özgü Osmanlı mimarisini taşıyan kule, Konak Meydanı\'nın merkezinde yer alır. Etrafındaki tarihi çevre, sahil şeridi ve işlek çarşıyla İzmir\'in en canlı noktasıdır.', latitude: 38.4117, longitude: 27.1379, address: 'Konak Meydanı, Konak/İzmir', rating: 4.6, reviewCount: 18400, visitDuration: '30-60 dk', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['saat kulesi', 'tarihi', 'Osmanlı', 'meydan', 'sahil'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1572963608396-44a1d02b1090?w=800&h=500&fit=crop' },
  { cityName: 'İzmir', name: 'Agora Açık Hava Müzesi', slug: 'izmir-agora', category: 'Müze', shortDescription: 'Antik İzmir\'in (Smyrna) kalbi.', description: 'İzmir Agorası, antik Smyrna şehrinin MÖ 4. yüzyıldan kalma agora (pazar yeri) kalıntılarıdır. Bazilika, stoa sütunları, heykeller ve yazıtlarla tarihin derinliklerine inmeyi sağlar. Şehir merkezinde yer alması nedeniyle kültür turunu yaparken kolayca uğranabilir.', latitude: 38.4153, longitude: 27.1397, address: 'Namazgah Mh., Konak/İzmir', rating: 4.5, reviewCount: 6800, visitDuration: '30-60 dk', entranceFee: '60 TL', openingHours: '08:00-19:00', tags: ['antik', 'agora', 'Roma', 'arkeoloji', 'Smyrna'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1590076215667-875c2717b81e?w=800&h=500&fit=crop' },

  // İstanbul (Ek Yerler)
  { cityName: 'İstanbul', name: 'Sultanahmet Camii (Mavi Cami)', slug: 'sultanahmet-camii', category: 'Tarihi', shortDescription: 'Altı minaresiyle Osmanlı mimarisinin şaheseri.', description: 'Sultanahmet Camii (Mavi Cami), 1616 yılında Sultan I. Ahmed tarafından yaptırılmıştır. İçerisindeki 20.000\'i aşkın mavi İznik çinisi nedeniyle "Mavi Cami" adıyla da bilinir. Altı minareli yapısıyla Osmanlı cami mimarisinin doruklarından kabul edilir. Ayasofya\'nın hemen karşısındaki konumu onu İstanbul\'un en çok ziyaret edilen noktalarından biri yapar.', latitude: 41.0054, longitude: 28.9768, address: 'Sultanahmet, Fatih/İstanbul', rating: 4.8, reviewCount: 52800, visitDuration: '30-60 dk', entranceFee: 'Ücretsiz', openingHours: 'Namaz aralarında ziyaret', tags: ['cami', 'Osmanlı', 'çini', 'mimari', 'tarihi'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&h=500&fit=crop' },
  { cityName: 'İstanbul', name: 'Dolmabahçe Sarayı', slug: 'dolmabahce-sarayi', category: 'Müze', shortDescription: 'Osmanlı\'nın Batı\'ya açılan görkemli sarayı.', description: 'Dolmabahçe Sarayı, 1856 yılında Boğaz kıyısına inşa edilmiş Osmanlı İmparatorluğu\'nun son sarayıdır. Avrupa barok mimarisini Osmanlı sanat anlayışıyla birleştiren saray, 285 oda ve 46 salon barındırır. İçerisindeki 4,5 tonluk kristal avize, dünyanın en büyük avizelerinden biridir. Atatürk\'ün hayatının son dönemlerini geçirdiği yer olması nedeniyle de tarihi öneme sahiptir.', latitude: 41.0393, longitude: 29.0007, address: 'Dolmabahçe Cd., Beşiktaş/İstanbul', rating: 4.7, reviewCount: 31200, visitDuration: '2-3 saat', entranceFee: '350 TL', openingHours: '09:00-16:00 (Pazartesi-Çarşamba kapalı)', tags: ['saray', 'Osmanlı', 'müze', 'Boğaz', 'Atatürk'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1580818144893-bc7cd8e75eba?w=800&h=500&fit=crop' },
  { cityName: 'İstanbul', name: 'Boğaz Turu', slug: 'bogaz-turu-istanbul', category: 'Doğa', shortDescription: 'İki kıtayı birbirine bağlayan efsanevi suyolunda tekne turu.', description: 'İstanbul Boğazı\'nda yapılan tekne turu, şehrin en eşsiz deneyimlerinden biridir. Avrupa ve Asya kıyılarındaki tarihi yalılar, köprüler, Rumeli ve Anadolu Hisarları, kümbet tepecikler ve mavinin tüm tonları bu turda görülebilir. Kısa süreli turlardan Karadeniz\'e uzanan uzun turlara kadar birçok seçenek mevcuttur.', latitude: 41.0612, longitude: 28.9999, address: 'Eminönü İskelesi, Fatih/İstanbul', rating: 4.7, reviewCount: 28900, visitDuration: '1.5-3 saat', entranceFee: '200-500 TL', openingHours: '09:00-20:00', tags: ['Boğaz', 'tekne', 'manzara', 'iki kıta', 'deniz'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&h=500&fit=crop' },
  { cityName: 'İstanbul', name: 'Prens Adaları', slug: 'prens-adalari', category: 'Doğa', shortDescription: 'Arabasız adalar, bisiklet ve fayton turu keyfi.', description: 'Prens Adaları, İstanbul\'a yakın 9 adadan oluşan takımadadır. Büyükada, Heybeliada, Burgazada ve Kınalıada en büyük adalar arasındadır. Adalarda motorlu araç yasaktır; ulaşım bisiklet ve faytonla sağlanır. Deniz manzarası, tarihi ahşap malikaneler, yürüyüş parkurları ve dingin atmosferiyle İstanbul\'un kalabalığından kaçmak için mükemmel noktalar.', latitude: 40.8708, longitude: 29.0934, address: 'Büyükada, İstanbul', rating: 4.7, reviewCount: 22000, visitDuration: 'Tam gün', entranceFee: 'Ücretsiz (vapur dahil değil)', openingHours: '24 saat', tags: ['ada', 'bisiklet', 'fayton', 'deniz', 'doğa'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1585936490174-9c2a9e2f2370?w=800&h=500&fit=crop' },

  // Antalya (Ek Yerler)
  { cityName: 'Antalya', name: 'Termessos Antik Kenti', slug: 'termessos-antik-kenti', category: 'Tarihi', shortDescription: 'Dağların zirvesinde yer alan, Büyük İskender\'i durdurmuş şehir.', description: 'Termessos, deniz seviyesinden 1.050 metre yüksekte Güllük Dağı\'nın zirvesine kurulmuş antik bir kenttir. Büyük İskender MÖ 333\'te bu kenti fetheden amamış ve "kartalın yuvası" olarak adlandırmıştır. Tiyatrosu, nekropolü, tapınak kalıntıları ve dağ manzarasıyla en etkileyici antik kentlerden biridir.', latitude: 37.1024, longitude: 30.4847, address: 'Güllük Dağı Milli Parkı, Korkuteli/Antalya', rating: 4.7, reviewCount: 5600, visitDuration: '2-3 saat', entranceFee: '60 TL', openingHours: '08:00-19:00', tags: ['antik kent', 'tiyatro', 'dağ', 'Roma', 'arkeoloji'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&h=500&fit=crop' },

  // Nevşehir (Ek Yerler)
  { cityName: 'Nevşehir', name: 'Kapadokya Balon Turu', slug: 'kapadokya-balon-turu', category: 'Doğa', shortDescription: 'Peri bacaları üzerinde efsanevi gün doğumu deneyimi.', description: 'Kapadokya\'da sıcak hava balonu ile uçuş, dünyanın önde gelen deneyim turları arasında gösterilir. Gün doğumunda başlayan turlar, peri bacaları, vadiler, üzüm bağları ve antik kaya kiliselerinin üzerinden saatlerce sürer. La Mancha Kappadokia, Voyager ve SunAir gibi onlarca şirket profesyonel pilot eşliğinde bu emsalsiz deneyimi sunar.', latitude: 38.6724, longitude: 34.8311, address: 'Göreme, Nevşehir', rating: 4.9, reviewCount: 38500, visitDuration: '1-1.5 saat (uçuş)', entranceFee: '4000-6000 TL', openingHours: 'Gün doğumu (mevsimsel)', tags: ['balon', 'Kapadokya', 'gün doğumu', 'macera', 'peri bacası'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?w=800&h=500&fit=crop' },

  // Artvin
  { cityName: 'Artvin', name: 'Artvin Kafkasör Yaylası', slug: 'kafkasor-yaylasi', category: 'Doğa', shortDescription: 'Büyük Kafkas coğrafyasında yeşilin tüm tonları.', description: 'Kafkasör Yaylası, Artvin ili sınırları içinde 1.900 metre yükseklikte yer alan ve Kafkas dağlarına komşu eşsiz bir yayla destinasyonudur. Her yıl geleneksel Kafkasör Kültür ve Sanat Festivali burada düzenlenir. Yörenin dağ panoramaları, endemik bitki örtüsü ve pastoral manzarası uzak doğa güzelliklerinin hayranlarını büyüler.', latitude: 41.1911, longitude: 41.8183, address: 'Kafkasör, Artvin Merkez', rating: 4.5, reviewCount: 4200, visitDuration: 'Yarım gün', entranceFee: 'Ücretsiz', openingHours: '24 saat', tags: ['yayla', 'Kafkas', 'doğa', 'festival', 'manzara'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&h=500&fit=crop' },

  // Muğla (Ek Yerler)
  { cityName: 'Muğla', name: 'Bodrum Kalesi', slug: 'bodrum-kalesi', category: 'Tarihi', shortDescription: 'Ege\'nin simgesi, deniz manzaralı Haçlı kalesi.', description: 'Bodrum Kalesi (Aziz Petrus Kalesi), Haçlı Şövalyeleri tarafından 15. yüzyılda dünyanın yedi harikasından biri olan Halikarnas Mausoleu\'nun taşlarıyla inşa edilmiştir. Günümüzde Sualtı Arkeoloji Müzesi olarak hizmet veren kale, Ege\'nin mavi sularına hakim konumu ve gün batımı manzarasıyla da ünlüdür.', latitude: 37.0342, longitude: 27.4248, address: 'Bodrum Kalesi, Muğla', rating: 4.7, reviewCount: 17600, visitDuration: '1-2 saat', entranceFee: '100 TL', openingHours: '09:00-19:00', tags: ['kale', 'müze', 'Haçlı', 'deniz', 'Ege'], isFeatured: true, imageUrl: 'https://images.unsplash.com/photo-1565117531832-fd4ad4f46e97?w=800&h=500&fit=crop' },
  { cityName: 'Muğla', name: 'Saklıkent Kanyonu', slug: 'saklikent-kanyonu', category: 'Doğa', shortDescription: 'Avrupa\'nın en uzun kanyonlarından, buz gibi su ve macera.', description: 'Saklıkent Kanyonu, 18 km uzunluğu ve 300 metre derinliğiyle Avrupa\'nın en uzun kanyonlarından biridir. Buz gibi dağ sularının aktığı kanyon içinde platform üzerinde yemek yemek, kanyona dalmak ve jeep safari turları son derece popülerdir. Muğla ilinin Fethiye ilçesine bağlı bu doğal tesçilli alan macera tutkunlarının gözdesidir.', latitude: 36.7086, longitude: 29.3078, address: 'Saklıkent, Fethiye/Muğla', rating: 4.6, reviewCount: 8900, visitDuration: '2-4 saat', entranceFee: '30 TL', openingHours: '08:00-20:00 (Nisan-Kasım)', tags: ['kanyon', 'macera', 'doğa', 'su', 'trekking'], isFeatured: false, imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=500&fit=crop' },
];

const seedPlaces = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('MongoDB Bağlandı');

    // Mevcut place verilerini temizle
    await Place.deleteMany({});
    console.log('Mevcut yer verileri temizlendi');

    // Ülkeyi bul (Türkiye)
    const turkey = await Country.findOne({ code: 'TR' });
    if (!turkey) {
      console.error('Türkiye ülke kaydı bulunamadı! Önce citySeeder çalıştırın.');
      process.exit(1);
    }

    // Tüm şehirleri al
    const allCities = await City.find({ country: turkey._id });
    const cityMap = {};
    allCities.forEach(city => {
      cityMap[city.name] = city._id;
    });

    let addedCount = 0;
    let skippedCount = 0;

    for (const placeData of placesData) {
      const cityId = cityMap[placeData.cityName];
      if (!cityId) {
        console.warn(`⚠️  Şehir bulunamadı: ${placeData.cityName} — atlandı`);
        skippedCount++;
        continue;
      }

      const { cityName, ...placeFields } = placeData;

      await Place.create({
        ...placeFields,
        city: cityId,
        country: turkey._id,
      });

      console.log(`✅ ${placeData.cityName} - ${placeData.name}`);
      addedCount++;
    }

    console.log(`\n🎉 ${addedCount} yer başarıyla eklendi! (${skippedCount} atlandı)`);

    await mongoose.connection.close();
    console.log('Veritabanı bağlantısı kapatıldı');
    process.exit(0);
  } catch (err) {
    console.error('Seed hatası:', err.message);
    process.exit(1);
  }
};

seedPlaces();
